// ------------------------------------------------------------------------------
//  <auto-generated>
//      Este código lo generó el generador de pruebas automatizadas de IU.
//      Versión: 16.0.0.0
//
//      Los cambios realizados en este archivo pueden provocar un comportamiento incorrecto y se perderán si
//      se vuelve a generar el código.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace CodedUITest_Gestion_Empleado
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.WinControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Generador de pruebas de UI codificadas", "16.0.31306.167")]
    public partial class UIMap
    {
        
        /// <summary>
        /// Listar Empleado,Registrar Empleados,Activar y Desactivar Empleados
        /// </summary>
        public void Recorded_Gestion_Empleado()
        {
            #region Variable Declarations
            WinEdit uIEditEdit = this.UIViewLogWindow.UIEntertextWindow.UIEditEdit;
            WinEdit uIEditEdit1 = this.UIViewLogWindow.UIEntertextWindow1.UIEditEdit;
            WinText uIIniciarSesionText = this.UIViewLogWindow.UIIniciarSesionWindow.UIIniciarSesionText;
            WinButton uIOKButton = this.UIOKWindow.UIOKButton;
            WinWindow uIGestionEmpleadoWindow = this.UIViewPrincipalWindow.UIGestionEmpleadoClient.UIGestionEmpleadoWindow;
            WinEdit uIEditEdit2 = this.UIViewPrincipalWindow.UIEntertextWindow.UIEditEdit;
            WinClient uIBtnBuscarClient = this.UIViewPrincipalWindow.UIBtnBuscarWindow.UIBtnBuscarClient;
            WinClient uITxtBuscarClient = this.UIViewPrincipalWindow.UITxtBuscarWindow.UITxtBuscarClient;
            WinClient uIBtnRegistrarClient = this.UIViewPrincipalWindow.UIBtnRegistrarWindow.UIBtnRegistrarClient;
            WinClient uITxtDNIClient = this.UIViewRegistroEmpleadoWindow.UITxtDNIWindow.UITxtDNIClient;
            WinEdit uIEditEdit3 = this.UIViewRegistroEmpleadoWindow.UIEntertextWindow.UIEditEdit;
            WinClient uITxtNombreClient = this.UIViewRegistroEmpleadoWindow.UITxtNombreWindow.UITxtNombreClient;
            WinEdit uIEditEdit4 = this.UIViewRegistroEmpleadoWindow.UIEntertextWindow1.UIEditEdit;
            WinEdit uIEditEdit5 = this.UIViewRegistroEmpleadoWindow.UIEntertextWindow2.UIEditEdit;
            WinEdit uIEditEdit6 = this.UIViewRegistroEmpleadoWindow.UIEntertextWindow3.UIEditEdit;
            WinClient uITxtCargoClient = this.UIViewRegistroEmpleadoWindow.UITxtCargoWindow.UITxtCargoClient;
            WinEdit uIEditEdit7 = this.UIViewRegistroEmpleadoWindow.UIEntertextWindow4.UIEditEdit;
            WinEdit uIEditEdit8 = this.UIViewRegistroEmpleadoWindow.UIEntertextWindow5.UIEditEdit;
            WinClient uITxtGmailClient = this.UIViewRegistroEmpleadoWindow.UITxtGmailWindow.UITxtGmailClient;
            WinEdit uIEditEdit9 = this.UIViewRegistroEmpleadoWindow.UIEntertextWindow6.UIEditEdit;
            WinClient uITxtTelefonoClient = this.UIViewRegistroEmpleadoWindow.UITxtTelefonoWindow.UITxtTelefonoClient;
            WinEdit uIEditEdit10 = this.UIViewRegistroEmpleadoWindow.UIEntertextWindow7.UIEditEdit;
            WinClient uITxtClaveClient = this.UIViewRegistroEmpleadoWindow.UITxtClaveWindow.UITxtClaveClient;
            WinEdit uIEditEdit11 = this.UIViewRegistroEmpleadoWindow.UIEntertextWindow8.UIEditEdit;
            WinClient uIRegistrarClient = this.UIViewRegistroEmpleadoWindow.UIBtnRegistrarWindow.UIRegistrarClient;
            WinButton uIOKButton1 = this.UIConfirmacionWindow.UIOKWindow.UIOKButton;
            WinColumnHeader uIIDEmpleadoColumnHeader = this.UIViewPrincipalWindow.UIDgvEmpleadosWindow.UIDataGridViewTable.UITopRowRow.UIIDEmpleadoColumnHeader;
            WinClient uIChkSeleccionarClient = this.UIViewPrincipalWindow.UIChkSeleccionarWindow.UIChkSeleccionarClient;
            WinCell uIFalseCell = this.UIViewPrincipalWindow.UIDgvEmpleadosWindow.UIDataGridViewTable.UIRow0Row.UIFalseCell;
            WinCell uIFalseCell1 = this.UIViewPrincipalWindow.UIDgvEmpleadosWindow.UIDataGridViewTable.UIRow1Row.UIFalseCell;
            WinText uIDesactivarText = this.UIViewPrincipalWindow.UIDesactivarWindow.UIDesactivarText;
            WinCell uIFalseCell2 = this.UIViewPrincipalWindow.UIDgvEmpleadosWindow.UIDataGridViewTable.UIRow0Row1.UIFalseCell;
            WinCell uIFalseCell3 = this.UIViewPrincipalWindow.UIDgvEmpleadosWindow.UIDataGridViewTable.UIRow1Row1.UIFalseCell;
            WinClient uIActivarClient = this.UIViewPrincipalWindow.UIBtnActivarWindow.UIActivarClient;
            #endregion

            // Iniciar '%USERPROFILE%\Downloads\DDD (1)\DDD\UI.Desktop\bin\Debug\UI.Desktop.exe'
            ApplicationUnderTest uIViewLogWindow = ApplicationUnderTest.Launch(this.Recorded_Gestion_EmpleadoParams.UIViewLogWindowExePath, this.Recorded_Gestion_EmpleadoParams.UIViewLogWindowAlternateExePath);

            // Escribir 'Admin' en cuadro de texto 'edit'
            uIEditEdit.Text = this.Recorded_Gestion_EmpleadoParams.UIEditEditText;

            // Escribir '123qweu0' en cuadro de texto 'edit'
            uIEditEdit1.Text = this.Recorded_Gestion_EmpleadoParams.UIEditEditText1;

            // Clic 'Iniciar Sesion' etiqueta
            Mouse.Click(uIIniciarSesionText, new Point(34, 6));

            // Clic 'OK' botón
            Mouse.Click(uIOKButton, new Point(37, 4));

            // Clic 'Gestion Empleado' ventana
            Mouse.Click(uIGestionEmpleadoWindow, new Point(83, 15));

            // Escribir '777777' en cuadro de texto 'edit'
            uIEditEdit2.Text = this.Recorded_Gestion_EmpleadoParams.UIEditEditText2;

            // Clic 'btnBuscar' cliente
            Mouse.Click(uIBtnBuscarClient, new Point(19, 16));

            // Mover  'edit' cuadro de texto a 'txtBuscar' cliente
            uITxtBuscarClient.EnsureClickable(new Point(1, 15));
            Mouse.StartDragging(uIEditEdit2, new Point(139, 13));
            Mouse.StopDragging(uITxtBuscarClient, new Point(1, 15));

            // Clic 'btnRegistrar' cliente
            Mouse.Click(uIBtnRegistrarClient, new Point(21, 28));

            // Clic 'txtDNI' cliente
            Mouse.Click(uITxtDNIClient, new Point(58, 3));

            // Escribir '888888' en cuadro de texto 'edit'
            uIEditEdit3.Text = this.Recorded_Gestion_EmpleadoParams.UIEditEditText3;

            // Clic 'txtNombre' cliente
            Mouse.Click(uITxtNombreClient, new Point(82, 6));

            // Escribir 'Santiago' en cuadro de texto 'edit'
            uIEditEdit4.Text = this.Recorded_Gestion_EmpleadoParams.UIEditEditText4;

            // Escribir 'Ramirez Gonzales' en cuadro de texto 'edit'
            uIEditEdit5.Text = this.Recorded_Gestion_EmpleadoParams.UIEditEditText5;

            // Escribir 'Encargado de Almacen' en cuadro de texto 'edit'
            uIEditEdit6.Text = this.Recorded_Gestion_EmpleadoParams.UIEditEditText6;

            // Doble clic 'txtCargo' cliente
            Mouse.DoubleClick(uITxtCargoClient, new Point(77, 8));

            // Escribir 'Almacen' en cuadro de texto 'edit'
            uIEditEdit7.Text = this.Recorded_Gestion_EmpleadoParams.UIEditEditText7;

            // Escribir 'Tacna' en cuadro de texto 'edit'
            uIEditEdit8.Text = this.Recorded_Gestion_EmpleadoParams.UIEditEditText8;

            // Doble clic 'txtGmail' cliente
            Mouse.DoubleClick(uITxtGmailClient, new Point(64, 6));

            // Escribir 'Santiago88' en cuadro de texto 'edit'
            uIEditEdit9.Text = this.Recorded_Gestion_EmpleadoParams.UIEditEditText9;

            // Clic 'txtTelefono' cliente
            Mouse.Click(uITxtTelefonoClient, new Point(78, 3));

            // Escribir '987654321' en cuadro de texto 'edit'
            uIEditEdit10.Text = this.Recorded_Gestion_EmpleadoParams.UIEditEditText10;

            // Clic 'txtClave' cliente
            Mouse.Click(uITxtClaveClient, new Point(93, 28));

            // Escribir '********' en cuadro de texto 'edit'
            Keyboard.SendKeys(uIEditEdit11, this.Recorded_Gestion_EmpleadoParams.UIEditEditSendKeys, true);

            // Clic 'Registrar' cliente
            Mouse.Click(uIRegistrarClient, new Point(32, 13));

            // Clic 'OK' botón
            Mouse.Click(uIOKButton1, new Point(32, 6));

            // Escribir 'Enter text' en cuadro de texto 'edit'
            uIEditEdit2.Text = this.Recorded_Gestion_EmpleadoParams.UIEditEditText11;

            // Clic 'btnBuscar' cliente
            Mouse.Click(uIBtnBuscarClient, new Point(14, 22));

            // Clic 'ID Empleado' encabezado de columna
            Mouse.Click(uIIDEmpleadoColumnHeader, new Point(105, 25));

            // Clic 'ID Empleado' encabezado de columna
            Mouse.Click(uIIDEmpleadoColumnHeader, new Point(98, 19));

            // Clic 'chkSeleccionar' cliente
            Mouse.Click(uIChkSeleccionarClient, new Point(10, 9));

            // Clic 'False' celda
            Mouse.Click(uIFalseCell, new Point(37, 17));

            // Clic 'False' celda
            Mouse.Click(uIFalseCell1, new Point(43, 23));

            // Clic 'Desactivar' etiqueta
            Mouse.Click(uIDesactivarText, new Point(3, 10));

            // Clic 'OK' botón
            Mouse.Click(uIOKButton, new Point(19, 10));

            // Clic 'btnBuscar' cliente
            Mouse.Click(uIBtnBuscarClient, new Point(21, 19));

            // Clic 'ID Empleado' encabezado de columna
            Mouse.Click(uIIDEmpleadoColumnHeader, new Point(145, 24));

            // Clic 'ID Empleado' encabezado de columna
            Mouse.Click(uIIDEmpleadoColumnHeader, new Point(127, 28));

            // Clic 'chkSeleccionar' cliente
            Mouse.Click(uIChkSeleccionarClient, new Point(16, 5));

            // Doble clic 'ID Empleado' encabezado de columna
            Mouse.DoubleClick(uIIDEmpleadoColumnHeader, new Point(44, 18));

            // Clic 'ID Empleado' encabezado de columna
            Mouse.Click(uIIDEmpleadoColumnHeader, new Point(45, 18));

            // Clic 'False' celda
            Mouse.Click(uIFalseCell2, new Point(42, 18));

            // Clic 'False' celda
            Mouse.Click(uIFalseCell3, new Point(40, 12));

            // Clic 'False' celda
            Mouse.Click(uIFalseCell3, new Point(40, 21));

            // Clic 'Activar' cliente
            Mouse.Click(uIActivarClient, new Point(67, 24));

            // Clic 'OK' botón
            Mouse.Click(uIOKButton, new Point(52, 9));

            // Clic 'btnBuscar' cliente
            Mouse.Click(uIBtnBuscarClient, new Point(11, 23));
        }
        
        #region Properties
        public virtual Recorded_Gestion_EmpleadoParams Recorded_Gestion_EmpleadoParams
        {
            get
            {
                if ((this.mRecorded_Gestion_EmpleadoParams == null))
                {
                    this.mRecorded_Gestion_EmpleadoParams = new Recorded_Gestion_EmpleadoParams();
                }
                return this.mRecorded_Gestion_EmpleadoParams;
            }
        }
        
        public UIViewLogWindow UIViewLogWindow
        {
            get
            {
                if ((this.mUIViewLogWindow == null))
                {
                    this.mUIViewLogWindow = new UIViewLogWindow();
                }
                return this.mUIViewLogWindow;
            }
        }
        
        public UIOKWindow UIOKWindow
        {
            get
            {
                if ((this.mUIOKWindow == null))
                {
                    this.mUIOKWindow = new UIOKWindow();
                }
                return this.mUIOKWindow;
            }
        }
        
        public UIViewPrincipalWindow UIViewPrincipalWindow
        {
            get
            {
                if ((this.mUIViewPrincipalWindow == null))
                {
                    this.mUIViewPrincipalWindow = new UIViewPrincipalWindow();
                }
                return this.mUIViewPrincipalWindow;
            }
        }
        
        public UIViewRegistroEmpleadoWindow UIViewRegistroEmpleadoWindow
        {
            get
            {
                if ((this.mUIViewRegistroEmpleadoWindow == null))
                {
                    this.mUIViewRegistroEmpleadoWindow = new UIViewRegistroEmpleadoWindow();
                }
                return this.mUIViewRegistroEmpleadoWindow;
            }
        }
        
        public UIConfirmacionWindow UIConfirmacionWindow
        {
            get
            {
                if ((this.mUIConfirmacionWindow == null))
                {
                    this.mUIConfirmacionWindow = new UIConfirmacionWindow();
                }
                return this.mUIConfirmacionWindow;
            }
        }
        #endregion
        
        #region Fields
        private Recorded_Gestion_EmpleadoParams mRecorded_Gestion_EmpleadoParams;
        
        private UIViewLogWindow mUIViewLogWindow;
        
        private UIOKWindow mUIOKWindow;
        
        private UIViewPrincipalWindow mUIViewPrincipalWindow;
        
        private UIViewRegistroEmpleadoWindow mUIViewRegistroEmpleadoWindow;
        
        private UIConfirmacionWindow mUIConfirmacionWindow;
        #endregion
    }
    
    /// <summary>
    /// Parámetros que se van a pasar a 'Recorded_Gestion_Empleado'
    /// </summary>
    [GeneratedCode("Generador de pruebas de UI codificadas", "16.0.31306.167")]
    public class Recorded_Gestion_EmpleadoParams
    {
        
        #region Fields
        /// <summary>
        /// Iniciar '%USERPROFILE%\Downloads\DDD (1)\DDD\UI.Desktop\bin\Debug\UI.Desktop.exe'
        /// </summary>
        public string UIViewLogWindowExePath = "C:\\Users\\USUARIO\\Downloads\\DDD (1)\\DDD\\UI.Desktop\\bin\\Debug\\UI.Desktop.exe";
        
        /// <summary>
        /// Iniciar '%USERPROFILE%\Downloads\DDD (1)\DDD\UI.Desktop\bin\Debug\UI.Desktop.exe'
        /// </summary>
        public string UIViewLogWindowAlternateExePath = "%USERPROFILE%\\Downloads\\DDD (1)\\DDD\\UI.Desktop\\bin\\Debug\\UI.Desktop.exe";
        
        /// <summary>
        /// Escribir 'Admin' en cuadro de texto 'edit'
        /// </summary>
        public string UIEditEditText = "Admin";
        
        /// <summary>
        /// Escribir '123qweu0' en cuadro de texto 'edit'
        /// </summary>
        public string UIEditEditText1 = "123qweu0";
        
        /// <summary>
        /// Escribir '777777' en cuadro de texto 'edit'
        /// </summary>
        public string UIEditEditText2 = "777777";
        
        /// <summary>
        /// Escribir '888888' en cuadro de texto 'edit'
        /// </summary>
        public string UIEditEditText3 = "888888";
        
        /// <summary>
        /// Escribir 'Santiago' en cuadro de texto 'edit'
        /// </summary>
        public string UIEditEditText4 = "Santiago";
        
        /// <summary>
        /// Escribir 'Ramirez Gonzales' en cuadro de texto 'edit'
        /// </summary>
        public string UIEditEditText5 = "Ramirez Gonzales";
        
        /// <summary>
        /// Escribir 'Encargado de Almacen' en cuadro de texto 'edit'
        /// </summary>
        public string UIEditEditText6 = "Encargado de Almacen";
        
        /// <summary>
        /// Escribir 'Almacen' en cuadro de texto 'edit'
        /// </summary>
        public string UIEditEditText7 = "Almacen";
        
        /// <summary>
        /// Escribir 'Tacna' en cuadro de texto 'edit'
        /// </summary>
        public string UIEditEditText8 = "Tacna";
        
        /// <summary>
        /// Escribir 'Santiago88' en cuadro de texto 'edit'
        /// </summary>
        public string UIEditEditText9 = "Santiago88";
        
        /// <summary>
        /// Escribir '987654321' en cuadro de texto 'edit'
        /// </summary>
        public string UIEditEditText10 = "987654321";
        
        /// <summary>
        /// Escribir '********' en cuadro de texto 'edit'
        /// </summary>
        public string UIEditEditSendKeys = "mOL/lXDUSd/hy7K5BZnJEA==";
        
        /// <summary>
        /// Escribir 'Enter text' en cuadro de texto 'edit'
        /// </summary>
        public string UIEditEditText11 = "Enter text";
        #endregion
    }
    
    [GeneratedCode("Generador de pruebas de UI codificadas", "16.0.31306.167")]
    public class UIViewLogWindow : WinWindow
    {
        
        public UIViewLogWindow()
        {
            #region Criterio de búsqueda
            this.SearchProperties[WinWindow.PropertyNames.Name] = "ViewLog";
            this.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.Window", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("ViewLog");
            #endregion
        }
        
        #region Properties
        public UIEntertextWindow UIEntertextWindow
        {
            get
            {
                if ((this.mUIEntertextWindow == null))
                {
                    this.mUIEntertextWindow = new UIEntertextWindow(this);
                }
                return this.mUIEntertextWindow;
            }
        }
        
        public UIEntertextWindow1 UIEntertextWindow1
        {
            get
            {
                if ((this.mUIEntertextWindow1 == null))
                {
                    this.mUIEntertextWindow1 = new UIEntertextWindow1(this);
                }
                return this.mUIEntertextWindow1;
            }
        }
        
        public UIIniciarSesionWindow UIIniciarSesionWindow
        {
            get
            {
                if ((this.mUIIniciarSesionWindow == null))
                {
                    this.mUIIniciarSesionWindow = new UIIniciarSesionWindow(this);
                }
                return this.mUIIniciarSesionWindow;
            }
        }
        #endregion
        
        #region Fields
        private UIEntertextWindow mUIEntertextWindow;
        
        private UIEntertextWindow1 mUIEntertextWindow1;
        
        private UIIniciarSesionWindow mUIIniciarSesionWindow;
        #endregion
    }
    
    [GeneratedCode("Generador de pruebas de UI codificadas", "16.0.31306.167")]
    public class UIEntertextWindow : WinWindow
    {
        
        public UIEntertextWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Criterio de búsqueda
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "edit";
            this.SearchProperties[WinWindow.PropertyNames.Instance] = "2";
            this.WindowTitles.Add("ViewLog");
            #endregion
        }
        
        #region Properties
        public WinEdit UIEditEdit
        {
            get
            {
                if ((this.mUIEditEdit == null))
                {
                    this.mUIEditEdit = new WinEdit(this);
                    #region Criterio de búsqueda
                    this.mUIEditEdit.WindowTitles.Add("ViewLog");
                    #endregion
                }
                return this.mUIEditEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUIEditEdit;
        #endregion
    }
    
    [GeneratedCode("Generador de pruebas de UI codificadas", "16.0.31306.167")]
    public class UIEntertextWindow1 : WinWindow
    {
        
        public UIEntertextWindow1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Criterio de búsqueda
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "edit";
            this.WindowTitles.Add("ViewLog");
            #endregion
        }
        
        #region Properties
        public WinEdit UIEditEdit
        {
            get
            {
                if ((this.mUIEditEdit == null))
                {
                    this.mUIEditEdit = new WinEdit(this);
                    #region Criterio de búsqueda
                    this.mUIEditEdit.WindowTitles.Add("ViewLog");
                    #endregion
                }
                return this.mUIEditEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUIEditEdit;
        #endregion
    }
    
    [GeneratedCode("Generador de pruebas de UI codificadas", "16.0.31306.167")]
    public class UIIniciarSesionWindow : WinWindow
    {
        
        public UIIniciarSesionWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Criterio de búsqueda
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "Label";
            this.WindowTitles.Add("ViewLog");
            #endregion
        }
        
        #region Properties
        public WinText UIIniciarSesionText
        {
            get
            {
                if ((this.mUIIniciarSesionText == null))
                {
                    this.mUIIniciarSesionText = new WinText(this);
                    #region Criterio de búsqueda
                    this.mUIIniciarSesionText.SearchProperties[WinText.PropertyNames.Name] = "Iniciar Sesion";
                    this.mUIIniciarSesionText.WindowTitles.Add("ViewLog");
                    #endregion
                }
                return this.mUIIniciarSesionText;
            }
        }
        #endregion
        
        #region Fields
        private WinText mUIIniciarSesionText;
        #endregion
    }
    
    [GeneratedCode("Generador de pruebas de UI codificadas", "16.0.31306.167")]
    public class UIOKWindow : WinWindow
    {
        
        public UIOKWindow()
        {
            #region Criterio de búsqueda
            this.SearchProperties[WinWindow.PropertyNames.Name] = "OK";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "Button";
            this.WindowTitles.Add("OK");
            #endregion
        }
        
        #region Properties
        public WinButton UIOKButton
        {
            get
            {
                if ((this.mUIOKButton == null))
                {
                    this.mUIOKButton = new WinButton(this);
                    #region Criterio de búsqueda
                    this.mUIOKButton.SearchProperties[WinButton.PropertyNames.Name] = "OK";
                    this.mUIOKButton.WindowTitles.Add("OK");
                    #endregion
                }
                return this.mUIOKButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIOKButton;
        #endregion
    }
    
    [GeneratedCode("Generador de pruebas de UI codificadas", "16.0.31306.167")]
    public class UIViewPrincipalWindow : WinWindow
    {
        
        public UIViewPrincipalWindow()
        {
            #region Criterio de búsqueda
            this.SearchProperties[WinWindow.PropertyNames.Name] = "ViewPrincipal";
            this.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.Window", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("ViewPrincipal");
            #endregion
        }
        
        #region Properties
        public UIGestionEmpleadoClient UIGestionEmpleadoClient
        {
            get
            {
                if ((this.mUIGestionEmpleadoClient == null))
                {
                    this.mUIGestionEmpleadoClient = new UIGestionEmpleadoClient(this);
                }
                return this.mUIGestionEmpleadoClient;
            }
        }
        
        public UIEntertextWindow2 UIEntertextWindow
        {
            get
            {
                if ((this.mUIEntertextWindow == null))
                {
                    this.mUIEntertextWindow = new UIEntertextWindow2(this);
                }
                return this.mUIEntertextWindow;
            }
        }
        
        public UIBtnBuscarWindow UIBtnBuscarWindow
        {
            get
            {
                if ((this.mUIBtnBuscarWindow == null))
                {
                    this.mUIBtnBuscarWindow = new UIBtnBuscarWindow(this);
                }
                return this.mUIBtnBuscarWindow;
            }
        }
        
        public UITxtBuscarWindow UITxtBuscarWindow
        {
            get
            {
                if ((this.mUITxtBuscarWindow == null))
                {
                    this.mUITxtBuscarWindow = new UITxtBuscarWindow(this);
                }
                return this.mUITxtBuscarWindow;
            }
        }
        
        public UIBtnRegistrarWindow UIBtnRegistrarWindow
        {
            get
            {
                if ((this.mUIBtnRegistrarWindow == null))
                {
                    this.mUIBtnRegistrarWindow = new UIBtnRegistrarWindow(this);
                }
                return this.mUIBtnRegistrarWindow;
            }
        }
        
        public UIDgvEmpleadosWindow UIDgvEmpleadosWindow
        {
            get
            {
                if ((this.mUIDgvEmpleadosWindow == null))
                {
                    this.mUIDgvEmpleadosWindow = new UIDgvEmpleadosWindow(this);
                }
                return this.mUIDgvEmpleadosWindow;
            }
        }
        
        public UIChkSeleccionarWindow UIChkSeleccionarWindow
        {
            get
            {
                if ((this.mUIChkSeleccionarWindow == null))
                {
                    this.mUIChkSeleccionarWindow = new UIChkSeleccionarWindow(this);
                }
                return this.mUIChkSeleccionarWindow;
            }
        }
        
        public UIDesactivarWindow UIDesactivarWindow
        {
            get
            {
                if ((this.mUIDesactivarWindow == null))
                {
                    this.mUIDesactivarWindow = new UIDesactivarWindow(this);
                }
                return this.mUIDesactivarWindow;
            }
        }
        
        public UIBtnActivarWindow UIBtnActivarWindow
        {
            get
            {
                if ((this.mUIBtnActivarWindow == null))
                {
                    this.mUIBtnActivarWindow = new UIBtnActivarWindow(this);
                }
                return this.mUIBtnActivarWindow;
            }
        }
        #endregion
        
        #region Fields
        private UIGestionEmpleadoClient mUIGestionEmpleadoClient;
        
        private UIEntertextWindow2 mUIEntertextWindow;
        
        private UIBtnBuscarWindow mUIBtnBuscarWindow;
        
        private UITxtBuscarWindow mUITxtBuscarWindow;
        
        private UIBtnRegistrarWindow mUIBtnRegistrarWindow;
        
        private UIDgvEmpleadosWindow mUIDgvEmpleadosWindow;
        
        private UIChkSeleccionarWindow mUIChkSeleccionarWindow;
        
        private UIDesactivarWindow mUIDesactivarWindow;
        
        private UIBtnActivarWindow mUIBtnActivarWindow;
        #endregion
    }
    
    [GeneratedCode("Generador de pruebas de UI codificadas", "16.0.31306.167")]
    public class UIGestionEmpleadoClient : WinClient
    {
        
        public UIGestionEmpleadoClient(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Criterio de búsqueda
            this.SearchProperties[WinControl.PropertyNames.Name] = "Gestion Empleado";
            this.WindowTitles.Add("ViewPrincipal");
            #endregion
        }
        
        #region Properties
        public WinWindow UIGestionEmpleadoWindow
        {
            get
            {
                if ((this.mUIGestionEmpleadoWindow == null))
                {
                    this.mUIGestionEmpleadoWindow = new WinWindow(this);
                    #region Criterio de búsqueda
                    this.mUIGestionEmpleadoWindow.SearchProperties[WinWindow.PropertyNames.Name] = "Gestion Empleado";
                    this.mUIGestionEmpleadoWindow.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.STATIC", PropertyExpressionOperator.Contains));
                    this.mUIGestionEmpleadoWindow.WindowTitles.Add("ViewPrincipal");
                    #endregion
                }
                return this.mUIGestionEmpleadoWindow;
            }
        }
        #endregion
        
        #region Fields
        private WinWindow mUIGestionEmpleadoWindow;
        #endregion
    }
    
    [GeneratedCode("Generador de pruebas de UI codificadas", "16.0.31306.167")]
    public class UIEntertextWindow2 : WinWindow
    {
        
        public UIEntertextWindow2(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Criterio de búsqueda
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "edit";
            this.WindowTitles.Add("ViewPrincipal");
            #endregion
        }
        
        #region Properties
        public WinEdit UIEditEdit
        {
            get
            {
                if ((this.mUIEditEdit == null))
                {
                    this.mUIEditEdit = new WinEdit(this);
                    #region Criterio de búsqueda
                    this.mUIEditEdit.WindowTitles.Add("ViewPrincipal");
                    #endregion
                }
                return this.mUIEditEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUIEditEdit;
        #endregion
    }
    
    [GeneratedCode("Generador de pruebas de UI codificadas", "16.0.31306.167")]
    public class UIBtnBuscarWindow : WinWindow
    {
        
        public UIBtnBuscarWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Criterio de búsqueda
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "btnBuscar";
            this.WindowTitles.Add("ViewPrincipal");
            #endregion
        }
        
        #region Properties
        public WinClient UIBtnBuscarClient
        {
            get
            {
                if ((this.mUIBtnBuscarClient == null))
                {
                    this.mUIBtnBuscarClient = new WinClient(this);
                    #region Criterio de búsqueda
                    this.mUIBtnBuscarClient.WindowTitles.Add("ViewPrincipal");
                    #endregion
                }
                return this.mUIBtnBuscarClient;
            }
        }
        #endregion
        
        #region Fields
        private WinClient mUIBtnBuscarClient;
        #endregion
    }
    
    [GeneratedCode("Generador de pruebas de UI codificadas", "16.0.31306.167")]
    public class UITxtBuscarWindow : WinWindow
    {
        
        public UITxtBuscarWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Criterio de búsqueda
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "txtBuscar";
            this.WindowTitles.Add("ViewPrincipal");
            #endregion
        }
        
        #region Properties
        public WinClient UITxtBuscarClient
        {
            get
            {
                if ((this.mUITxtBuscarClient == null))
                {
                    this.mUITxtBuscarClient = new WinClient(this);
                    #region Criterio de búsqueda
                    this.mUITxtBuscarClient.WindowTitles.Add("ViewPrincipal");
                    #endregion
                }
                return this.mUITxtBuscarClient;
            }
        }
        #endregion
        
        #region Fields
        private WinClient mUITxtBuscarClient;
        #endregion
    }
    
    [GeneratedCode("Generador de pruebas de UI codificadas", "16.0.31306.167")]
    public class UIBtnRegistrarWindow : WinWindow
    {
        
        public UIBtnRegistrarWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Criterio de búsqueda
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "btnRegistrar";
            this.WindowTitles.Add("ViewPrincipal");
            #endregion
        }
        
        #region Properties
        public WinClient UIBtnRegistrarClient
        {
            get
            {
                if ((this.mUIBtnRegistrarClient == null))
                {
                    this.mUIBtnRegistrarClient = new WinClient(this);
                    #region Criterio de búsqueda
                    this.mUIBtnRegistrarClient.WindowTitles.Add("ViewPrincipal");
                    #endregion
                }
                return this.mUIBtnRegistrarClient;
            }
        }
        #endregion
        
        #region Fields
        private WinClient mUIBtnRegistrarClient;
        #endregion
    }
    
    [GeneratedCode("Generador de pruebas de UI codificadas", "16.0.31306.167")]
    public class UIDgvEmpleadosWindow : WinWindow
    {
        
        public UIDgvEmpleadosWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Criterio de búsqueda
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "dgvEmpleados";
            this.WindowTitles.Add("ViewPrincipal");
            #endregion
        }
        
        #region Properties
        public UIDataGridViewTable UIDataGridViewTable
        {
            get
            {
                if ((this.mUIDataGridViewTable == null))
                {
                    this.mUIDataGridViewTable = new UIDataGridViewTable(this);
                }
                return this.mUIDataGridViewTable;
            }
        }
        #endregion
        
        #region Fields
        private UIDataGridViewTable mUIDataGridViewTable;
        #endregion
    }
    
    [GeneratedCode("Generador de pruebas de UI codificadas", "16.0.31306.167")]
    public class UIDataGridViewTable : WinTable
    {
        
        public UIDataGridViewTable(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Criterio de búsqueda
            this.SearchProperties[WinTable.PropertyNames.Name] = "DataGridView";
            this.WindowTitles.Add("ViewPrincipal");
            #endregion
        }
        
        #region Properties
        public UITopRowRow UITopRowRow
        {
            get
            {
                if ((this.mUITopRowRow == null))
                {
                    this.mUITopRowRow = new UITopRowRow(this);
                }
                return this.mUITopRowRow;
            }
        }
        
        public UIRow0Row UIRow0Row
        {
            get
            {
                if ((this.mUIRow0Row == null))
                {
                    this.mUIRow0Row = new UIRow0Row(this);
                }
                return this.mUIRow0Row;
            }
        }
        
        public UIRow1Row UIRow1Row
        {
            get
            {
                if ((this.mUIRow1Row == null))
                {
                    this.mUIRow1Row = new UIRow1Row(this);
                }
                return this.mUIRow1Row;
            }
        }
        
        public UIRow0Row1 UIRow0Row1
        {
            get
            {
                if ((this.mUIRow0Row1 == null))
                {
                    this.mUIRow0Row1 = new UIRow0Row1(this);
                }
                return this.mUIRow0Row1;
            }
        }
        
        public UIRow1Row1 UIRow1Row1
        {
            get
            {
                if ((this.mUIRow1Row1 == null))
                {
                    this.mUIRow1Row1 = new UIRow1Row1(this);
                }
                return this.mUIRow1Row1;
            }
        }
        #endregion
        
        #region Fields
        private UITopRowRow mUITopRowRow;
        
        private UIRow0Row mUIRow0Row;
        
        private UIRow1Row mUIRow1Row;
        
        private UIRow0Row1 mUIRow0Row1;
        
        private UIRow1Row1 mUIRow1Row1;
        #endregion
    }
    
    [GeneratedCode("Generador de pruebas de UI codificadas", "16.0.31306.167")]
    public class UITopRowRow : WinRow
    {
        
        public UITopRowRow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Criterio de búsqueda
            this.SearchProperties[WinRow.PropertyNames.Name] = "Top Row";
            this.SearchConfigurations.Add(SearchConfiguration.AlwaysSearch);
            this.WindowTitles.Add("ViewPrincipal");
            #endregion
        }
        
        #region Properties
        public WinColumnHeader UIIDEmpleadoColumnHeader
        {
            get
            {
                if ((this.mUIIDEmpleadoColumnHeader == null))
                {
                    this.mUIIDEmpleadoColumnHeader = new WinColumnHeader(this);
                    #region Criterio de búsqueda
                    this.mUIIDEmpleadoColumnHeader.SearchProperties[WinControl.PropertyNames.Name] = "ID Empleado";
                    this.mUIIDEmpleadoColumnHeader.WindowTitles.Add("ViewPrincipal");
                    #endregion
                }
                return this.mUIIDEmpleadoColumnHeader;
            }
        }
        #endregion
        
        #region Fields
        private WinColumnHeader mUIIDEmpleadoColumnHeader;
        #endregion
    }
    
    [GeneratedCode("Generador de pruebas de UI codificadas", "16.0.31306.167")]
    public class UIRow0Row : WinRow
    {
        
        public UIRow0Row(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Criterio de búsqueda
            this.SearchProperties[WinRow.PropertyNames.Value] = "False;504;Santiago;Ramirez Gonzales;Almacen;Encargado de Almacen;Activado";
            this.SearchConfigurations.Add(SearchConfiguration.AlwaysSearch);
            this.WindowTitles.Add("ViewPrincipal");
            #endregion
        }
        
        #region Properties
        public WinCell UIFalseCell
        {
            get
            {
                if ((this.mUIFalseCell == null))
                {
                    this.mUIFalseCell = new WinCell(this);
                    #region Criterio de búsqueda
                    this.mUIFalseCell.SearchProperties[WinCell.PropertyNames.Value] = "False";
                    this.mUIFalseCell.WindowTitles.Add("ViewPrincipal");
                    #endregion
                }
                return this.mUIFalseCell;
            }
        }
        #endregion
        
        #region Fields
        private WinCell mUIFalseCell;
        #endregion
    }
    
    [GeneratedCode("Generador de pruebas de UI codificadas", "16.0.31306.167")]
    public class UIRow1Row : WinRow
    {
        
        public UIRow1Row(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Criterio de búsqueda
            this.SearchProperties[WinRow.PropertyNames.Value] = "False;503;Steve;Ramos;Encargado de Ventas;Ventas;Activado";
            this.SearchConfigurations.Add(SearchConfiguration.AlwaysSearch);
            this.WindowTitles.Add("ViewPrincipal");
            #endregion
        }
        
        #region Properties
        public WinCell UIFalseCell
        {
            get
            {
                if ((this.mUIFalseCell == null))
                {
                    this.mUIFalseCell = new WinCell(this);
                    #region Criterio de búsqueda
                    this.mUIFalseCell.SearchProperties[WinCell.PropertyNames.Value] = "False";
                    this.mUIFalseCell.WindowTitles.Add("ViewPrincipal");
                    #endregion
                }
                return this.mUIFalseCell;
            }
        }
        #endregion
        
        #region Fields
        private WinCell mUIFalseCell;
        #endregion
    }
    
    [GeneratedCode("Generador de pruebas de UI codificadas", "16.0.31306.167")]
    public class UIRow0Row1 : WinRow
    {
        
        public UIRow0Row1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Criterio de búsqueda
            this.SearchProperties[WinRow.PropertyNames.Value] = "False;504;Santiago;Ramirez Gonzales;Almacen;Encargado de Almacen;Desactivado";
            this.SearchConfigurations.Add(SearchConfiguration.AlwaysSearch);
            this.WindowTitles.Add("ViewPrincipal");
            #endregion
        }
        
        #region Properties
        public WinCell UIFalseCell
        {
            get
            {
                if ((this.mUIFalseCell == null))
                {
                    this.mUIFalseCell = new WinCell(this);
                    #region Criterio de búsqueda
                    this.mUIFalseCell.SearchProperties[WinCell.PropertyNames.Value] = "False";
                    this.mUIFalseCell.WindowTitles.Add("ViewPrincipal");
                    #endregion
                }
                return this.mUIFalseCell;
            }
        }
        #endregion
        
        #region Fields
        private WinCell mUIFalseCell;
        #endregion
    }
    
    [GeneratedCode("Generador de pruebas de UI codificadas", "16.0.31306.167")]
    public class UIRow1Row1 : WinRow
    {
        
        public UIRow1Row1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Criterio de búsqueda
            this.SearchProperties[WinRow.PropertyNames.Value] = "False;503;Steve;Ramos;Encargado de Ventas;Ventas;Desactivado";
            this.SearchConfigurations.Add(SearchConfiguration.AlwaysSearch);
            this.WindowTitles.Add("ViewPrincipal");
            #endregion
        }
        
        #region Properties
        public WinCell UIFalseCell
        {
            get
            {
                if ((this.mUIFalseCell == null))
                {
                    this.mUIFalseCell = new WinCell(this);
                    #region Criterio de búsqueda
                    this.mUIFalseCell.SearchProperties[WinCell.PropertyNames.Value] = "False";
                    this.mUIFalseCell.WindowTitles.Add("ViewPrincipal");
                    #endregion
                }
                return this.mUIFalseCell;
            }
        }
        #endregion
        
        #region Fields
        private WinCell mUIFalseCell;
        #endregion
    }
    
    [GeneratedCode("Generador de pruebas de UI codificadas", "16.0.31306.167")]
    public class UIChkSeleccionarWindow : WinWindow
    {
        
        public UIChkSeleccionarWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Criterio de búsqueda
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "chkSeleccionar";
            this.WindowTitles.Add("ViewPrincipal");
            #endregion
        }
        
        #region Properties
        public WinClient UIChkSeleccionarClient
        {
            get
            {
                if ((this.mUIChkSeleccionarClient == null))
                {
                    this.mUIChkSeleccionarClient = new WinClient(this);
                    #region Criterio de búsqueda
                    this.mUIChkSeleccionarClient.WindowTitles.Add("ViewPrincipal");
                    #endregion
                }
                return this.mUIChkSeleccionarClient;
            }
        }
        #endregion
        
        #region Fields
        private WinClient mUIChkSeleccionarClient;
        #endregion
    }
    
    [GeneratedCode("Generador de pruebas de UI codificadas", "16.0.31306.167")]
    public class UIDesactivarWindow : WinWindow
    {
        
        public UIDesactivarWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Criterio de búsqueda
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "Label";
            this.WindowTitles.Add("ViewPrincipal");
            #endregion
        }
        
        #region Properties
        public WinText UIDesactivarText
        {
            get
            {
                if ((this.mUIDesactivarText == null))
                {
                    this.mUIDesactivarText = new WinText(this);
                    #region Criterio de búsqueda
                    this.mUIDesactivarText.SearchProperties[WinText.PropertyNames.Name] = "Desactivar";
                    this.mUIDesactivarText.WindowTitles.Add("ViewPrincipal");
                    #endregion
                }
                return this.mUIDesactivarText;
            }
        }
        #endregion
        
        #region Fields
        private WinText mUIDesactivarText;
        #endregion
    }
    
    [GeneratedCode("Generador de pruebas de UI codificadas", "16.0.31306.167")]
    public class UIBtnActivarWindow : WinWindow
    {
        
        public UIBtnActivarWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Criterio de búsqueda
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "btnActivar";
            this.WindowTitles.Add("ViewPrincipal");
            #endregion
        }
        
        #region Properties
        public WinClient UIActivarClient
        {
            get
            {
                if ((this.mUIActivarClient == null))
                {
                    this.mUIActivarClient = new WinClient(this);
                    #region Criterio de búsqueda
                    this.mUIActivarClient.SearchProperties[WinControl.PropertyNames.Name] = "Activar";
                    this.mUIActivarClient.WindowTitles.Add("ViewPrincipal");
                    #endregion
                }
                return this.mUIActivarClient;
            }
        }
        #endregion
        
        #region Fields
        private WinClient mUIActivarClient;
        #endregion
    }
    
    [GeneratedCode("Generador de pruebas de UI codificadas", "16.0.31306.167")]
    public class UIViewRegistroEmpleadoWindow : WinWindow
    {
        
        public UIViewRegistroEmpleadoWindow()
        {
            #region Criterio de búsqueda
            this.SearchProperties[WinWindow.PropertyNames.Name] = "ViewRegistroEmpleado";
            this.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.Window", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("ViewRegistroEmpleado");
            #endregion
        }
        
        #region Properties
        public UITxtDNIWindow UITxtDNIWindow
        {
            get
            {
                if ((this.mUITxtDNIWindow == null))
                {
                    this.mUITxtDNIWindow = new UITxtDNIWindow(this);
                }
                return this.mUITxtDNIWindow;
            }
        }
        
        public UIEntertextWindow3 UIEntertextWindow
        {
            get
            {
                if ((this.mUIEntertextWindow == null))
                {
                    this.mUIEntertextWindow = new UIEntertextWindow3(this);
                }
                return this.mUIEntertextWindow;
            }
        }
        
        public UITxtNombreWindow UITxtNombreWindow
        {
            get
            {
                if ((this.mUITxtNombreWindow == null))
                {
                    this.mUITxtNombreWindow = new UITxtNombreWindow(this);
                }
                return this.mUITxtNombreWindow;
            }
        }
        
        public UIEntertextWindow11 UIEntertextWindow1
        {
            get
            {
                if ((this.mUIEntertextWindow1 == null))
                {
                    this.mUIEntertextWindow1 = new UIEntertextWindow11(this);
                }
                return this.mUIEntertextWindow1;
            }
        }
        
        public UIEntertextWindow21 UIEntertextWindow2
        {
            get
            {
                if ((this.mUIEntertextWindow2 == null))
                {
                    this.mUIEntertextWindow2 = new UIEntertextWindow21(this);
                }
                return this.mUIEntertextWindow2;
            }
        }
        
        public UIEntertextWindow31 UIEntertextWindow3
        {
            get
            {
                if ((this.mUIEntertextWindow3 == null))
                {
                    this.mUIEntertextWindow3 = new UIEntertextWindow31(this);
                }
                return this.mUIEntertextWindow3;
            }
        }
        
        public UITxtCargoWindow UITxtCargoWindow
        {
            get
            {
                if ((this.mUITxtCargoWindow == null))
                {
                    this.mUITxtCargoWindow = new UITxtCargoWindow(this);
                }
                return this.mUITxtCargoWindow;
            }
        }
        
        public UIEntertextWindow4 UIEntertextWindow4
        {
            get
            {
                if ((this.mUIEntertextWindow4 == null))
                {
                    this.mUIEntertextWindow4 = new UIEntertextWindow4(this);
                }
                return this.mUIEntertextWindow4;
            }
        }
        
        public UIEntertextWindow5 UIEntertextWindow5
        {
            get
            {
                if ((this.mUIEntertextWindow5 == null))
                {
                    this.mUIEntertextWindow5 = new UIEntertextWindow5(this);
                }
                return this.mUIEntertextWindow5;
            }
        }
        
        public UITxtGmailWindow UITxtGmailWindow
        {
            get
            {
                if ((this.mUITxtGmailWindow == null))
                {
                    this.mUITxtGmailWindow = new UITxtGmailWindow(this);
                }
                return this.mUITxtGmailWindow;
            }
        }
        
        public UIEntertextWindow6 UIEntertextWindow6
        {
            get
            {
                if ((this.mUIEntertextWindow6 == null))
                {
                    this.mUIEntertextWindow6 = new UIEntertextWindow6(this);
                }
                return this.mUIEntertextWindow6;
            }
        }
        
        public UITxtTelefonoWindow UITxtTelefonoWindow
        {
            get
            {
                if ((this.mUITxtTelefonoWindow == null))
                {
                    this.mUITxtTelefonoWindow = new UITxtTelefonoWindow(this);
                }
                return this.mUITxtTelefonoWindow;
            }
        }
        
        public UIEntertextWindow7 UIEntertextWindow7
        {
            get
            {
                if ((this.mUIEntertextWindow7 == null))
                {
                    this.mUIEntertextWindow7 = new UIEntertextWindow7(this);
                }
                return this.mUIEntertextWindow7;
            }
        }
        
        public UITxtClaveWindow UITxtClaveWindow
        {
            get
            {
                if ((this.mUITxtClaveWindow == null))
                {
                    this.mUITxtClaveWindow = new UITxtClaveWindow(this);
                }
                return this.mUITxtClaveWindow;
            }
        }
        
        public UIEntertextWindow8 UIEntertextWindow8
        {
            get
            {
                if ((this.mUIEntertextWindow8 == null))
                {
                    this.mUIEntertextWindow8 = new UIEntertextWindow8(this);
                }
                return this.mUIEntertextWindow8;
            }
        }
        
        public UIBtnRegistrarWindow1 UIBtnRegistrarWindow
        {
            get
            {
                if ((this.mUIBtnRegistrarWindow == null))
                {
                    this.mUIBtnRegistrarWindow = new UIBtnRegistrarWindow1(this);
                }
                return this.mUIBtnRegistrarWindow;
            }
        }
        #endregion
        
        #region Fields
        private UITxtDNIWindow mUITxtDNIWindow;
        
        private UIEntertextWindow3 mUIEntertextWindow;
        
        private UITxtNombreWindow mUITxtNombreWindow;
        
        private UIEntertextWindow11 mUIEntertextWindow1;
        
        private UIEntertextWindow21 mUIEntertextWindow2;
        
        private UIEntertextWindow31 mUIEntertextWindow3;
        
        private UITxtCargoWindow mUITxtCargoWindow;
        
        private UIEntertextWindow4 mUIEntertextWindow4;
        
        private UIEntertextWindow5 mUIEntertextWindow5;
        
        private UITxtGmailWindow mUITxtGmailWindow;
        
        private UIEntertextWindow6 mUIEntertextWindow6;
        
        private UITxtTelefonoWindow mUITxtTelefonoWindow;
        
        private UIEntertextWindow7 mUIEntertextWindow7;
        
        private UITxtClaveWindow mUITxtClaveWindow;
        
        private UIEntertextWindow8 mUIEntertextWindow8;
        
        private UIBtnRegistrarWindow1 mUIBtnRegistrarWindow;
        #endregion
    }
    
    [GeneratedCode("Generador de pruebas de UI codificadas", "16.0.31306.167")]
    public class UITxtDNIWindow : WinWindow
    {
        
        public UITxtDNIWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Criterio de búsqueda
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "txtDNI";
            this.WindowTitles.Add("ViewRegistroEmpleado");
            #endregion
        }
        
        #region Properties
        public WinClient UITxtDNIClient
        {
            get
            {
                if ((this.mUITxtDNIClient == null))
                {
                    this.mUITxtDNIClient = new WinClient(this);
                    #region Criterio de búsqueda
                    this.mUITxtDNIClient.WindowTitles.Add("ViewRegistroEmpleado");
                    #endregion
                }
                return this.mUITxtDNIClient;
            }
        }
        #endregion
        
        #region Fields
        private WinClient mUITxtDNIClient;
        #endregion
    }
    
    [GeneratedCode("Generador de pruebas de UI codificadas", "16.0.31306.167")]
    public class UIEntertextWindow3 : WinWindow
    {
        
        public UIEntertextWindow3(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Criterio de búsqueda
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "edit";
            this.SearchProperties[WinWindow.PropertyNames.Instance] = "9";
            this.WindowTitles.Add("ViewRegistroEmpleado");
            #endregion
        }
        
        #region Properties
        public WinEdit UIEditEdit
        {
            get
            {
                if ((this.mUIEditEdit == null))
                {
                    this.mUIEditEdit = new WinEdit(this);
                    #region Criterio de búsqueda
                    this.mUIEditEdit.WindowTitles.Add("ViewRegistroEmpleado");
                    #endregion
                }
                return this.mUIEditEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUIEditEdit;
        #endregion
    }
    
    [GeneratedCode("Generador de pruebas de UI codificadas", "16.0.31306.167")]
    public class UITxtNombreWindow : WinWindow
    {
        
        public UITxtNombreWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Criterio de búsqueda
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "txtNombre";
            this.WindowTitles.Add("ViewRegistroEmpleado");
            #endregion
        }
        
        #region Properties
        public WinClient UITxtNombreClient
        {
            get
            {
                if ((this.mUITxtNombreClient == null))
                {
                    this.mUITxtNombreClient = new WinClient(this);
                    #region Criterio de búsqueda
                    this.mUITxtNombreClient.WindowTitles.Add("ViewRegistroEmpleado");
                    #endregion
                }
                return this.mUITxtNombreClient;
            }
        }
        #endregion
        
        #region Fields
        private WinClient mUITxtNombreClient;
        #endregion
    }
    
    [GeneratedCode("Generador de pruebas de UI codificadas", "16.0.31306.167")]
    public class UIEntertextWindow11 : WinWindow
    {
        
        public UIEntertextWindow11(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Criterio de búsqueda
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "edit";
            this.SearchProperties[WinWindow.PropertyNames.Instance] = "8";
            this.WindowTitles.Add("ViewRegistroEmpleado");
            #endregion
        }
        
        #region Properties
        public WinEdit UIEditEdit
        {
            get
            {
                if ((this.mUIEditEdit == null))
                {
                    this.mUIEditEdit = new WinEdit(this);
                    #region Criterio de búsqueda
                    this.mUIEditEdit.WindowTitles.Add("ViewRegistroEmpleado");
                    #endregion
                }
                return this.mUIEditEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUIEditEdit;
        #endregion
    }
    
    [GeneratedCode("Generador de pruebas de UI codificadas", "16.0.31306.167")]
    public class UIEntertextWindow21 : WinWindow
    {
        
        public UIEntertextWindow21(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Criterio de búsqueda
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "edit";
            this.SearchProperties[WinWindow.PropertyNames.Instance] = "7";
            this.WindowTitles.Add("ViewRegistroEmpleado");
            #endregion
        }
        
        #region Properties
        public WinEdit UIEditEdit
        {
            get
            {
                if ((this.mUIEditEdit == null))
                {
                    this.mUIEditEdit = new WinEdit(this);
                    #region Criterio de búsqueda
                    this.mUIEditEdit.WindowTitles.Add("ViewRegistroEmpleado");
                    #endregion
                }
                return this.mUIEditEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUIEditEdit;
        #endregion
    }
    
    [GeneratedCode("Generador de pruebas de UI codificadas", "16.0.31306.167")]
    public class UIEntertextWindow31 : WinWindow
    {
        
        public UIEntertextWindow31(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Criterio de búsqueda
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "edit";
            this.SearchProperties[WinWindow.PropertyNames.Instance] = "2";
            this.WindowTitles.Add("ViewRegistroEmpleado");
            #endregion
        }
        
        #region Properties
        public WinEdit UIEditEdit
        {
            get
            {
                if ((this.mUIEditEdit == null))
                {
                    this.mUIEditEdit = new WinEdit(this);
                    #region Criterio de búsqueda
                    this.mUIEditEdit.WindowTitles.Add("ViewRegistroEmpleado");
                    #endregion
                }
                return this.mUIEditEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUIEditEdit;
        #endregion
    }
    
    [GeneratedCode("Generador de pruebas de UI codificadas", "16.0.31306.167")]
    public class UITxtCargoWindow : WinWindow
    {
        
        public UITxtCargoWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Criterio de búsqueda
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "txtCargo";
            this.WindowTitles.Add("ViewRegistroEmpleado");
            #endregion
        }
        
        #region Properties
        public WinClient UITxtCargoClient
        {
            get
            {
                if ((this.mUITxtCargoClient == null))
                {
                    this.mUITxtCargoClient = new WinClient(this);
                    #region Criterio de búsqueda
                    this.mUITxtCargoClient.WindowTitles.Add("ViewRegistroEmpleado");
                    #endregion
                }
                return this.mUITxtCargoClient;
            }
        }
        #endregion
        
        #region Fields
        private WinClient mUITxtCargoClient;
        #endregion
    }
    
    [GeneratedCode("Generador de pruebas de UI codificadas", "16.0.31306.167")]
    public class UIEntertextWindow4 : WinWindow
    {
        
        public UIEntertextWindow4(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Criterio de búsqueda
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "edit";
            this.WindowTitles.Add("ViewRegistroEmpleado");
            #endregion
        }
        
        #region Properties
        public WinEdit UIEditEdit
        {
            get
            {
                if ((this.mUIEditEdit == null))
                {
                    this.mUIEditEdit = new WinEdit(this);
                    #region Criterio de búsqueda
                    this.mUIEditEdit.WindowTitles.Add("ViewRegistroEmpleado");
                    #endregion
                }
                return this.mUIEditEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUIEditEdit;
        #endregion
    }
    
    [GeneratedCode("Generador de pruebas de UI codificadas", "16.0.31306.167")]
    public class UIEntertextWindow5 : WinWindow
    {
        
        public UIEntertextWindow5(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Criterio de búsqueda
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "edit";
            this.SearchProperties[WinWindow.PropertyNames.Instance] = "6";
            this.WindowTitles.Add("ViewRegistroEmpleado");
            #endregion
        }
        
        #region Properties
        public WinEdit UIEditEdit
        {
            get
            {
                if ((this.mUIEditEdit == null))
                {
                    this.mUIEditEdit = new WinEdit(this);
                    #region Criterio de búsqueda
                    this.mUIEditEdit.WindowTitles.Add("ViewRegistroEmpleado");
                    #endregion
                }
                return this.mUIEditEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUIEditEdit;
        #endregion
    }
    
    [GeneratedCode("Generador de pruebas de UI codificadas", "16.0.31306.167")]
    public class UITxtGmailWindow : WinWindow
    {
        
        public UITxtGmailWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Criterio de búsqueda
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "txtGmail";
            this.WindowTitles.Add("ViewRegistroEmpleado");
            #endregion
        }
        
        #region Properties
        public WinClient UITxtGmailClient
        {
            get
            {
                if ((this.mUITxtGmailClient == null))
                {
                    this.mUITxtGmailClient = new WinClient(this);
                    #region Criterio de búsqueda
                    this.mUITxtGmailClient.WindowTitles.Add("ViewRegistroEmpleado");
                    #endregion
                }
                return this.mUITxtGmailClient;
            }
        }
        #endregion
        
        #region Fields
        private WinClient mUITxtGmailClient;
        #endregion
    }
    
    [GeneratedCode("Generador de pruebas de UI codificadas", "16.0.31306.167")]
    public class UIEntertextWindow6 : WinWindow
    {
        
        public UIEntertextWindow6(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Criterio de búsqueda
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "edit";
            this.SearchProperties[WinWindow.PropertyNames.Instance] = "5";
            this.WindowTitles.Add("ViewRegistroEmpleado");
            #endregion
        }
        
        #region Properties
        public WinEdit UIEditEdit
        {
            get
            {
                if ((this.mUIEditEdit == null))
                {
                    this.mUIEditEdit = new WinEdit(this);
                    #region Criterio de búsqueda
                    this.mUIEditEdit.WindowTitles.Add("ViewRegistroEmpleado");
                    #endregion
                }
                return this.mUIEditEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUIEditEdit;
        #endregion
    }
    
    [GeneratedCode("Generador de pruebas de UI codificadas", "16.0.31306.167")]
    public class UITxtTelefonoWindow : WinWindow
    {
        
        public UITxtTelefonoWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Criterio de búsqueda
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "txtTelefono";
            this.WindowTitles.Add("ViewRegistroEmpleado");
            #endregion
        }
        
        #region Properties
        public WinClient UITxtTelefonoClient
        {
            get
            {
                if ((this.mUITxtTelefonoClient == null))
                {
                    this.mUITxtTelefonoClient = new WinClient(this);
                    #region Criterio de búsqueda
                    this.mUITxtTelefonoClient.WindowTitles.Add("ViewRegistroEmpleado");
                    #endregion
                }
                return this.mUITxtTelefonoClient;
            }
        }
        #endregion
        
        #region Fields
        private WinClient mUITxtTelefonoClient;
        #endregion
    }
    
    [GeneratedCode("Generador de pruebas de UI codificadas", "16.0.31306.167")]
    public class UIEntertextWindow7 : WinWindow
    {
        
        public UIEntertextWindow7(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Criterio de búsqueda
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "edit";
            this.SearchProperties[WinWindow.PropertyNames.Instance] = "4";
            this.WindowTitles.Add("ViewRegistroEmpleado");
            #endregion
        }
        
        #region Properties
        public WinEdit UIEditEdit
        {
            get
            {
                if ((this.mUIEditEdit == null))
                {
                    this.mUIEditEdit = new WinEdit(this);
                    #region Criterio de búsqueda
                    this.mUIEditEdit.WindowTitles.Add("ViewRegistroEmpleado");
                    #endregion
                }
                return this.mUIEditEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUIEditEdit;
        #endregion
    }
    
    [GeneratedCode("Generador de pruebas de UI codificadas", "16.0.31306.167")]
    public class UITxtClaveWindow : WinWindow
    {
        
        public UITxtClaveWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Criterio de búsqueda
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "txtClave";
            this.WindowTitles.Add("ViewRegistroEmpleado");
            #endregion
        }
        
        #region Properties
        public WinClient UITxtClaveClient
        {
            get
            {
                if ((this.mUITxtClaveClient == null))
                {
                    this.mUITxtClaveClient = new WinClient(this);
                    #region Criterio de búsqueda
                    this.mUITxtClaveClient.WindowTitles.Add("ViewRegistroEmpleado");
                    #endregion
                }
                return this.mUITxtClaveClient;
            }
        }
        #endregion
        
        #region Fields
        private WinClient mUITxtClaveClient;
        #endregion
    }
    
    [GeneratedCode("Generador de pruebas de UI codificadas", "16.0.31306.167")]
    public class UIEntertextWindow8 : WinWindow
    {
        
        public UIEntertextWindow8(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Criterio de búsqueda
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "edit";
            this.SearchProperties[WinWindow.PropertyNames.Instance] = "3";
            this.WindowTitles.Add("ViewRegistroEmpleado");
            #endregion
        }
        
        #region Properties
        public WinEdit UIEditEdit
        {
            get
            {
                if ((this.mUIEditEdit == null))
                {
                    this.mUIEditEdit = new WinEdit(this);
                    #region Criterio de búsqueda
                    this.mUIEditEdit.WindowTitles.Add("ViewRegistroEmpleado");
                    #endregion
                }
                return this.mUIEditEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUIEditEdit;
        #endregion
    }
    
    [GeneratedCode("Generador de pruebas de UI codificadas", "16.0.31306.167")]
    public class UIBtnRegistrarWindow1 : WinWindow
    {
        
        public UIBtnRegistrarWindow1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Criterio de búsqueda
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "btnRegistrar";
            this.WindowTitles.Add("ViewRegistroEmpleado");
            #endregion
        }
        
        #region Properties
        public WinClient UIRegistrarClient
        {
            get
            {
                if ((this.mUIRegistrarClient == null))
                {
                    this.mUIRegistrarClient = new WinClient(this);
                    #region Criterio de búsqueda
                    this.mUIRegistrarClient.SearchProperties[WinControl.PropertyNames.Name] = "Registrar";
                    this.mUIRegistrarClient.WindowTitles.Add("ViewRegistroEmpleado");
                    #endregion
                }
                return this.mUIRegistrarClient;
            }
        }
        #endregion
        
        #region Fields
        private WinClient mUIRegistrarClient;
        #endregion
    }
    
    [GeneratedCode("Generador de pruebas de UI codificadas", "16.0.31306.167")]
    public class UIConfirmacionWindow : WinWindow
    {
        
        public UIConfirmacionWindow()
        {
            #region Criterio de búsqueda
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Confirmacion";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "#32770";
            this.WindowTitles.Add("Confirmacion");
            #endregion
        }
        
        #region Properties
        public UIOKWindow1 UIOKWindow
        {
            get
            {
                if ((this.mUIOKWindow == null))
                {
                    this.mUIOKWindow = new UIOKWindow1(this);
                }
                return this.mUIOKWindow;
            }
        }
        #endregion
        
        #region Fields
        private UIOKWindow1 mUIOKWindow;
        #endregion
    }
    
    [GeneratedCode("Generador de pruebas de UI codificadas", "16.0.31306.167")]
    public class UIOKWindow1 : WinWindow
    {
        
        public UIOKWindow1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Criterio de búsqueda
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "2";
            this.WindowTitles.Add("Confirmacion");
            #endregion
        }
        
        #region Properties
        public WinButton UIOKButton
        {
            get
            {
                if ((this.mUIOKButton == null))
                {
                    this.mUIOKButton = new WinButton(this);
                    #region Criterio de búsqueda
                    this.mUIOKButton.SearchProperties[WinButton.PropertyNames.Name] = "OK";
                    this.mUIOKButton.WindowTitles.Add("Confirmacion");
                    #endregion
                }
                return this.mUIOKButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIOKButton;
        #endregion
    }
}
