// ------------------------------------------------------------------------------
//  <auto-generated>
//      Este código lo generó el generador de pruebas automatizadas de IU.
//      Versión: 16.0.0.0
//
//      Los cambios realizados en este archivo pueden provocar un comportamiento incorrecto y se perderán si
//      se vuelve a generar el código.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace CodedUITest_Registro_Pedido
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.WinControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Generador de pruebas de UI codificadas", "16.0.31306.167")]
    public partial class UIMap
    {
        
        /// <summary>
        /// BUscar Cliente , Agregar Material , Crear Venta
        /// </summary>
        public void Recorded_Registro_Pedido()
        {
            #region Variable Declarations
            WinEdit uIEditEdit = this.UIViewLogWindow.UIEntertextWindow.UIEditEdit;
            WinEdit uIEditEdit1 = this.UIViewLogWindow.UIEntertextWindow1.UIEditEdit;
            WinText uIIniciarSesionText = this.UIViewLogWindow.UIIniciarSesionWindow.UIIniciarSesionText;
            WinButton uIOKButton = this.UIOKWindow.UIOKButton;
            WinClient uIRegistroPedidoClient = this.UIViewPrincipalWindow.UIBtnRPWindow.UIRegistroPedidoClient;
            WinEdit uIEditEdit2 = this.UIViewPrincipalWindow.UIEntertextWindow.UIEditEdit;
            WinClient uIBtnBuscarClient = this.UIViewPrincipalWindow.UIBtnBuscarWindow.UIBtnBuscarClient;
            WinText uIAgregarText = this.UIViewPrincipalWindow.UIAgregarWindow.UIAgregarText;
            WinTitleBar uIViewDetallePedidoTitleBar = this.UIViewDetallePedidoWindow.UIViewDetallePedidoTitleBar;
            WinEdit uIEditEdit3 = this.UIViewDetallePedidoWindow.UIEntertextWindow.UIEditEdit;
            WinWindow uIEntertextWindow = this.UIViewDetallePedidoWindow.UITxtcantidadWindow.UIEntertextWindow;
            WinEdit uIEditEdit4 = this.UIViewDetallePedidoWindow.UIEntertextWindow1.UIEditEdit;
            WinClient uIBtnBuscarClient1 = this.UIViewDetallePedidoWindow.UIBtnBuscarWindow.UIBtnBuscarClient;
            WinClient uIAgregarClient = this.UIViewDetallePedidoWindow.UIBtnAgregarWindow.UIAgregarClient;
            WinClient uIListarClient = this.UIViewPrincipalWindow.UIBtnListarWindow.UIListarClient;
            WinEdit uIEditEdit5 = this.UIViewDetallePedidoWindow1.UIEntertextWindow.UIEditEdit;
            WinEdit uIEditEdit6 = this.UIViewDetallePedidoWindow1.UIEntertextWindow1.UIEditEdit;
            WinClient uIBtnBuscarClient2 = this.UIViewDetallePedidoWindow1.UIBtnBuscarWindow.UIBtnBuscarClient;
            WinClient uIAgregarClient1 = this.UIViewDetallePedidoWindow1.UIBtnAgregarWindow.UIAgregarClient;
            WinClient uICrearVentaClient = this.UIViewPrincipalWindow.UIBtnCrearVentaWindow.UICrearVentaClient;
            #endregion

            // Iniciar '%USERPROFILE%\Downloads\DDD (1)\DDD\UI.Desktop\bin\Debug\UI.Desktop.exe'
            ApplicationUnderTest uIViewLogWindow = ApplicationUnderTest.Launch(this.Recorded_Registro_PedidoParams.UIViewLogWindowExePath, this.Recorded_Registro_PedidoParams.UIViewLogWindowAlternateExePath);

            // Escribir 'Admin' en cuadro de texto 'edit'
            uIEditEdit.Text = this.Recorded_Registro_PedidoParams.UIEditEditText;

            // Escribir '1' en cuadro de texto 'edit'
            Keyboard.SendKeys(uIEditEdit, this.Recorded_Registro_PedidoParams.UIEditEditSendKeys, ModifierKeys.None);

            // Escribir '123qweu0' en cuadro de texto 'edit'
            uIEditEdit1.Text = this.Recorded_Registro_PedidoParams.UIEditEditText1;

            // Clic 'Iniciar Sesion' etiqueta
            Mouse.Click(uIIniciarSesionText, new Point(27, 14));

            // Clic 'OK' botón
            Mouse.Click(uIOKButton, new Point(51, 11));

            // Clic 'Registro Pedido' cliente
            Mouse.Click(uIRegistroPedidoClient, new Point(115, 8));

            // Escribir '27' en cuadro de texto 'edit'
            uIEditEdit2.Text = this.Recorded_Registro_PedidoParams.UIEditEditText2;

            // Clic 'btnBuscar' cliente
            Mouse.Click(uIBtnBuscarClient, new Point(10, 17));

            // Clic 'Agregar' etiqueta
            Mouse.Click(uIAgregarText, new Point(39, 7));

            // Clic 'ViewDetallePedido' barra de título
            Mouse.Click(uIViewDetallePedidoTitleBar, new Point(267, 19));

            // Escribir 'Tela Verde' en cuadro de texto 'edit'
            uIEditEdit3.Text = this.Recorded_Registro_PedidoParams.UIEditEditText3;

            // Clic 'Enter text' ventana
            Mouse.Click(uIEntertextWindow, new Point(63, 17));

            // Escribir '3' en cuadro de texto 'edit'
            uIEditEdit4.Text = this.Recorded_Registro_PedidoParams.UIEditEditText4;

            // Clic 'btnBuscar' cliente
            Mouse.Click(uIBtnBuscarClient1, new Point(7, 4));

            // Clic 'Agregar' cliente
            Mouse.Click(uIAgregarClient, new Point(110, 20));

            // Clic 'Listar' cliente
            Mouse.Click(uIListarClient, new Point(29, 11));

            // Clic 'Agregar' etiqueta
            Mouse.Click(uIAgregarText, new Point(2, 8));

            // Escribir 'Tela Roja' en cuadro de texto 'edit'
            uIEditEdit5.Text = this.Recorded_Registro_PedidoParams.UIEditEditText5;

            // Escribir '6' en cuadro de texto 'edit'
            uIEditEdit6.Text = this.Recorded_Registro_PedidoParams.UIEditEditText6;

            // Clic 'btnBuscar' cliente
            Mouse.Click(uIBtnBuscarClient2, new Point(14, 8));

            // Clic 'OK' botón
            Mouse.Click(uIOKButton, new Point(13, 9));

            // Escribir 'Tela Azul' en cuadro de texto 'edit'
            uIEditEdit5.Text = this.Recorded_Registro_PedidoParams.UIEditEditText7;

            // Clic 'btnBuscar' cliente
            Mouse.Click(uIBtnBuscarClient2, new Point(6, 13));

            // Clic 'Agregar' cliente
            Mouse.Click(uIAgregarClient1, new Point(127, 22));

            // Clic 'Listar' cliente
            Mouse.Click(uIListarClient, new Point(30, 8));

            // Clic 'Crear Venta' cliente
            Mouse.Click(uICrearVentaClient, new Point(99, 19));
        }
        
        #region Properties
        public virtual Recorded_Registro_PedidoParams Recorded_Registro_PedidoParams
        {
            get
            {
                if ((this.mRecorded_Registro_PedidoParams == null))
                {
                    this.mRecorded_Registro_PedidoParams = new Recorded_Registro_PedidoParams();
                }
                return this.mRecorded_Registro_PedidoParams;
            }
        }
        
        public UIViewLogWindow UIViewLogWindow
        {
            get
            {
                if ((this.mUIViewLogWindow == null))
                {
                    this.mUIViewLogWindow = new UIViewLogWindow();
                }
                return this.mUIViewLogWindow;
            }
        }
        
        public UIOKWindow UIOKWindow
        {
            get
            {
                if ((this.mUIOKWindow == null))
                {
                    this.mUIOKWindow = new UIOKWindow();
                }
                return this.mUIOKWindow;
            }
        }
        
        public UIViewPrincipalWindow UIViewPrincipalWindow
        {
            get
            {
                if ((this.mUIViewPrincipalWindow == null))
                {
                    this.mUIViewPrincipalWindow = new UIViewPrincipalWindow();
                }
                return this.mUIViewPrincipalWindow;
            }
        }
        
        public UIViewDetallePedidoWindow UIViewDetallePedidoWindow
        {
            get
            {
                if ((this.mUIViewDetallePedidoWindow == null))
                {
                    this.mUIViewDetallePedidoWindow = new UIViewDetallePedidoWindow();
                }
                return this.mUIViewDetallePedidoWindow;
            }
        }
        
        public UIViewDetallePedidoWindow1 UIViewDetallePedidoWindow1
        {
            get
            {
                if ((this.mUIViewDetallePedidoWindow1 == null))
                {
                    this.mUIViewDetallePedidoWindow1 = new UIViewDetallePedidoWindow1();
                }
                return this.mUIViewDetallePedidoWindow1;
            }
        }
        #endregion
        
        #region Fields
        private Recorded_Registro_PedidoParams mRecorded_Registro_PedidoParams;
        
        private UIViewLogWindow mUIViewLogWindow;
        
        private UIOKWindow mUIOKWindow;
        
        private UIViewPrincipalWindow mUIViewPrincipalWindow;
        
        private UIViewDetallePedidoWindow mUIViewDetallePedidoWindow;
        
        private UIViewDetallePedidoWindow1 mUIViewDetallePedidoWindow1;
        #endregion
    }
    
    /// <summary>
    /// Parámetros que se van a pasar a 'Recorded_Registro_Pedido'
    /// </summary>
    [GeneratedCode("Generador de pruebas de UI codificadas", "16.0.31306.167")]
    public class Recorded_Registro_PedidoParams
    {
        
        #region Fields
        /// <summary>
        /// Iniciar '%USERPROFILE%\Downloads\DDD (1)\DDD\UI.Desktop\bin\Debug\UI.Desktop.exe'
        /// </summary>
        public string UIViewLogWindowExePath = "C:\\Users\\USUARIO\\Downloads\\DDD (1)\\DDD\\UI.Desktop\\bin\\Debug\\UI.Desktop.exe";
        
        /// <summary>
        /// Iniciar '%USERPROFILE%\Downloads\DDD (1)\DDD\UI.Desktop\bin\Debug\UI.Desktop.exe'
        /// </summary>
        public string UIViewLogWindowAlternateExePath = "%USERPROFILE%\\Downloads\\DDD (1)\\DDD\\UI.Desktop\\bin\\Debug\\UI.Desktop.exe";
        
        /// <summary>
        /// Escribir 'Admin' en cuadro de texto 'edit'
        /// </summary>
        public string UIEditEditText = "Admin";
        
        /// <summary>
        /// Escribir '1' en cuadro de texto 'edit'
        /// </summary>
        public string UIEditEditSendKeys = "1";
        
        /// <summary>
        /// Escribir '123qweu0' en cuadro de texto 'edit'
        /// </summary>
        public string UIEditEditText1 = "123qweu0";
        
        /// <summary>
        /// Escribir '27' en cuadro de texto 'edit'
        /// </summary>
        public string UIEditEditText2 = "27";
        
        /// <summary>
        /// Escribir 'Tela Verde' en cuadro de texto 'edit'
        /// </summary>
        public string UIEditEditText3 = "Tela Verde";
        
        /// <summary>
        /// Escribir '3' en cuadro de texto 'edit'
        /// </summary>
        public string UIEditEditText4 = "3";
        
        /// <summary>
        /// Escribir 'Tela Roja' en cuadro de texto 'edit'
        /// </summary>
        public string UIEditEditText5 = "Tela Roja";
        
        /// <summary>
        /// Escribir '6' en cuadro de texto 'edit'
        /// </summary>
        public string UIEditEditText6 = "6";
        
        /// <summary>
        /// Escribir 'Tela Azul' en cuadro de texto 'edit'
        /// </summary>
        public string UIEditEditText7 = "Tela Azul";
        #endregion
    }
    
    [GeneratedCode("Generador de pruebas de UI codificadas", "16.0.31306.167")]
    public class UIViewLogWindow : WinWindow
    {
        
        public UIViewLogWindow()
        {
            #region Criterio de búsqueda
            this.SearchProperties[WinWindow.PropertyNames.Name] = "ViewLog";
            this.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.Window", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("ViewLog");
            #endregion
        }
        
        #region Properties
        public UIEntertextWindow UIEntertextWindow
        {
            get
            {
                if ((this.mUIEntertextWindow == null))
                {
                    this.mUIEntertextWindow = new UIEntertextWindow(this);
                }
                return this.mUIEntertextWindow;
            }
        }
        
        public UIEntertextWindow1 UIEntertextWindow1
        {
            get
            {
                if ((this.mUIEntertextWindow1 == null))
                {
                    this.mUIEntertextWindow1 = new UIEntertextWindow1(this);
                }
                return this.mUIEntertextWindow1;
            }
        }
        
        public UIIniciarSesionWindow UIIniciarSesionWindow
        {
            get
            {
                if ((this.mUIIniciarSesionWindow == null))
                {
                    this.mUIIniciarSesionWindow = new UIIniciarSesionWindow(this);
                }
                return this.mUIIniciarSesionWindow;
            }
        }
        #endregion
        
        #region Fields
        private UIEntertextWindow mUIEntertextWindow;
        
        private UIEntertextWindow1 mUIEntertextWindow1;
        
        private UIIniciarSesionWindow mUIIniciarSesionWindow;
        #endregion
    }
    
    [GeneratedCode("Generador de pruebas de UI codificadas", "16.0.31306.167")]
    public class UIEntertextWindow : WinWindow
    {
        
        public UIEntertextWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Criterio de búsqueda
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "edit";
            this.SearchProperties[WinWindow.PropertyNames.Instance] = "2";
            this.WindowTitles.Add("ViewLog");
            #endregion
        }
        
        #region Properties
        public WinEdit UIEditEdit
        {
            get
            {
                if ((this.mUIEditEdit == null))
                {
                    this.mUIEditEdit = new WinEdit(this);
                    #region Criterio de búsqueda
                    this.mUIEditEdit.WindowTitles.Add("ViewLog");
                    #endregion
                }
                return this.mUIEditEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUIEditEdit;
        #endregion
    }
    
    [GeneratedCode("Generador de pruebas de UI codificadas", "16.0.31306.167")]
    public class UIEntertextWindow1 : WinWindow
    {
        
        public UIEntertextWindow1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Criterio de búsqueda
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "edit";
            this.WindowTitles.Add("ViewLog");
            #endregion
        }
        
        #region Properties
        public WinEdit UIEditEdit
        {
            get
            {
                if ((this.mUIEditEdit == null))
                {
                    this.mUIEditEdit = new WinEdit(this);
                    #region Criterio de búsqueda
                    this.mUIEditEdit.WindowTitles.Add("ViewLog");
                    #endregion
                }
                return this.mUIEditEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUIEditEdit;
        #endregion
    }
    
    [GeneratedCode("Generador de pruebas de UI codificadas", "16.0.31306.167")]
    public class UIIniciarSesionWindow : WinWindow
    {
        
        public UIIniciarSesionWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Criterio de búsqueda
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "Label";
            this.WindowTitles.Add("ViewLog");
            #endregion
        }
        
        #region Properties
        public WinText UIIniciarSesionText
        {
            get
            {
                if ((this.mUIIniciarSesionText == null))
                {
                    this.mUIIniciarSesionText = new WinText(this);
                    #region Criterio de búsqueda
                    this.mUIIniciarSesionText.SearchProperties[WinText.PropertyNames.Name] = "Iniciar Sesion";
                    this.mUIIniciarSesionText.WindowTitles.Add("ViewLog");
                    #endregion
                }
                return this.mUIIniciarSesionText;
            }
        }
        #endregion
        
        #region Fields
        private WinText mUIIniciarSesionText;
        #endregion
    }
    
    [GeneratedCode("Generador de pruebas de UI codificadas", "16.0.31306.167")]
    public class UIOKWindow : WinWindow
    {
        
        public UIOKWindow()
        {
            #region Criterio de búsqueda
            this.SearchProperties[WinWindow.PropertyNames.Name] = "OK";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "Button";
            this.WindowTitles.Add("OK");
            #endregion
        }
        
        #region Properties
        public WinButton UIOKButton
        {
            get
            {
                if ((this.mUIOKButton == null))
                {
                    this.mUIOKButton = new WinButton(this);
                    #region Criterio de búsqueda
                    this.mUIOKButton.SearchProperties[WinButton.PropertyNames.Name] = "OK";
                    this.mUIOKButton.WindowTitles.Add("OK");
                    #endregion
                }
                return this.mUIOKButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIOKButton;
        #endregion
    }
    
    [GeneratedCode("Generador de pruebas de UI codificadas", "16.0.31306.167")]
    public class UIViewPrincipalWindow : WinWindow
    {
        
        public UIViewPrincipalWindow()
        {
            #region Criterio de búsqueda
            this.SearchProperties[WinWindow.PropertyNames.Name] = "ViewPrincipal";
            this.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.Window", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("ViewPrincipal");
            #endregion
        }
        
        #region Properties
        public UIBtnRPWindow UIBtnRPWindow
        {
            get
            {
                if ((this.mUIBtnRPWindow == null))
                {
                    this.mUIBtnRPWindow = new UIBtnRPWindow(this);
                }
                return this.mUIBtnRPWindow;
            }
        }
        
        public UIEntertextWindow2 UIEntertextWindow
        {
            get
            {
                if ((this.mUIEntertextWindow == null))
                {
                    this.mUIEntertextWindow = new UIEntertextWindow2(this);
                }
                return this.mUIEntertextWindow;
            }
        }
        
        public UIBtnBuscarWindow UIBtnBuscarWindow
        {
            get
            {
                if ((this.mUIBtnBuscarWindow == null))
                {
                    this.mUIBtnBuscarWindow = new UIBtnBuscarWindow(this);
                }
                return this.mUIBtnBuscarWindow;
            }
        }
        
        public UIAgregarWindow UIAgregarWindow
        {
            get
            {
                if ((this.mUIAgregarWindow == null))
                {
                    this.mUIAgregarWindow = new UIAgregarWindow(this);
                }
                return this.mUIAgregarWindow;
            }
        }
        
        public UIBtnListarWindow UIBtnListarWindow
        {
            get
            {
                if ((this.mUIBtnListarWindow == null))
                {
                    this.mUIBtnListarWindow = new UIBtnListarWindow(this);
                }
                return this.mUIBtnListarWindow;
            }
        }
        
        public UIBtnCrearVentaWindow UIBtnCrearVentaWindow
        {
            get
            {
                if ((this.mUIBtnCrearVentaWindow == null))
                {
                    this.mUIBtnCrearVentaWindow = new UIBtnCrearVentaWindow(this);
                }
                return this.mUIBtnCrearVentaWindow;
            }
        }
        #endregion
        
        #region Fields
        private UIBtnRPWindow mUIBtnRPWindow;
        
        private UIEntertextWindow2 mUIEntertextWindow;
        
        private UIBtnBuscarWindow mUIBtnBuscarWindow;
        
        private UIAgregarWindow mUIAgregarWindow;
        
        private UIBtnListarWindow mUIBtnListarWindow;
        
        private UIBtnCrearVentaWindow mUIBtnCrearVentaWindow;
        #endregion
    }
    
    [GeneratedCode("Generador de pruebas de UI codificadas", "16.0.31306.167")]
    public class UIBtnRPWindow : WinWindow
    {
        
        public UIBtnRPWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Criterio de búsqueda
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "btnRP";
            this.WindowTitles.Add("ViewPrincipal");
            #endregion
        }
        
        #region Properties
        public WinClient UIRegistroPedidoClient
        {
            get
            {
                if ((this.mUIRegistroPedidoClient == null))
                {
                    this.mUIRegistroPedidoClient = new WinClient(this);
                    #region Criterio de búsqueda
                    this.mUIRegistroPedidoClient.SearchProperties[WinControl.PropertyNames.Name] = "Registro Pedido";
                    this.mUIRegistroPedidoClient.WindowTitles.Add("ViewPrincipal");
                    #endregion
                }
                return this.mUIRegistroPedidoClient;
            }
        }
        #endregion
        
        #region Fields
        private WinClient mUIRegistroPedidoClient;
        #endregion
    }
    
    [GeneratedCode("Generador de pruebas de UI codificadas", "16.0.31306.167")]
    public class UIEntertextWindow2 : WinWindow
    {
        
        public UIEntertextWindow2(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Criterio de búsqueda
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "edit";
            this.SearchProperties[WinWindow.PropertyNames.Instance] = "5";
            this.WindowTitles.Add("ViewPrincipal");
            #endregion
        }
        
        #region Properties
        public WinEdit UIEditEdit
        {
            get
            {
                if ((this.mUIEditEdit == null))
                {
                    this.mUIEditEdit = new WinEdit(this);
                    #region Criterio de búsqueda
                    this.mUIEditEdit.WindowTitles.Add("ViewPrincipal");
                    #endregion
                }
                return this.mUIEditEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUIEditEdit;
        #endregion
    }
    
    [GeneratedCode("Generador de pruebas de UI codificadas", "16.0.31306.167")]
    public class UIBtnBuscarWindow : WinWindow
    {
        
        public UIBtnBuscarWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Criterio de búsqueda
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "btnBuscar";
            this.WindowTitles.Add("ViewPrincipal");
            #endregion
        }
        
        #region Properties
        public WinClient UIBtnBuscarClient
        {
            get
            {
                if ((this.mUIBtnBuscarClient == null))
                {
                    this.mUIBtnBuscarClient = new WinClient(this);
                    #region Criterio de búsqueda
                    this.mUIBtnBuscarClient.WindowTitles.Add("ViewPrincipal");
                    #endregion
                }
                return this.mUIBtnBuscarClient;
            }
        }
        #endregion
        
        #region Fields
        private WinClient mUIBtnBuscarClient;
        #endregion
    }
    
    [GeneratedCode("Generador de pruebas de UI codificadas", "16.0.31306.167")]
    public class UIAgregarWindow : WinWindow
    {
        
        public UIAgregarWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Criterio de búsqueda
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "Label";
            this.SearchProperties[WinWindow.PropertyNames.Instance] = "3";
            this.WindowTitles.Add("ViewPrincipal");
            #endregion
        }
        
        #region Properties
        public WinText UIAgregarText
        {
            get
            {
                if ((this.mUIAgregarText == null))
                {
                    this.mUIAgregarText = new WinText(this);
                    #region Criterio de búsqueda
                    this.mUIAgregarText.SearchProperties[WinText.PropertyNames.Name] = "Agregar ";
                    this.mUIAgregarText.WindowTitles.Add("ViewPrincipal");
                    #endregion
                }
                return this.mUIAgregarText;
            }
        }
        #endregion
        
        #region Fields
        private WinText mUIAgregarText;
        #endregion
    }
    
    [GeneratedCode("Generador de pruebas de UI codificadas", "16.0.31306.167")]
    public class UIBtnListarWindow : WinWindow
    {
        
        public UIBtnListarWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Criterio de búsqueda
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "btnListar";
            this.WindowTitles.Add("ViewPrincipal");
            #endregion
        }
        
        #region Properties
        public WinClient UIListarClient
        {
            get
            {
                if ((this.mUIListarClient == null))
                {
                    this.mUIListarClient = new WinClient(this);
                    #region Criterio de búsqueda
                    this.mUIListarClient.SearchProperties[WinControl.PropertyNames.Name] = "Listar";
                    this.mUIListarClient.WindowTitles.Add("ViewPrincipal");
                    #endregion
                }
                return this.mUIListarClient;
            }
        }
        #endregion
        
        #region Fields
        private WinClient mUIListarClient;
        #endregion
    }
    
    [GeneratedCode("Generador de pruebas de UI codificadas", "16.0.31306.167")]
    public class UIBtnCrearVentaWindow : WinWindow
    {
        
        public UIBtnCrearVentaWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Criterio de búsqueda
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "btnCrearVenta";
            this.WindowTitles.Add("ViewPrincipal");
            #endregion
        }
        
        #region Properties
        public WinClient UICrearVentaClient
        {
            get
            {
                if ((this.mUICrearVentaClient == null))
                {
                    this.mUICrearVentaClient = new WinClient(this);
                    #region Criterio de búsqueda
                    this.mUICrearVentaClient.SearchProperties[WinControl.PropertyNames.Name] = "Crear Venta";
                    this.mUICrearVentaClient.WindowTitles.Add("ViewPrincipal");
                    #endregion
                }
                return this.mUICrearVentaClient;
            }
        }
        #endregion
        
        #region Fields
        private WinClient mUICrearVentaClient;
        #endregion
    }
    
    [GeneratedCode("Generador de pruebas de UI codificadas", "16.0.31306.167")]
    public class UIViewDetallePedidoWindow : WinWindow
    {
        
        public UIViewDetallePedidoWindow()
        {
            #region Criterio de búsqueda
            this.SearchProperties[WinWindow.PropertyNames.Name] = "ViewDetallePedido";
            this.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.Window", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("ViewDetallePedido");
            #endregion
        }
        
        #region Properties
        public WinTitleBar UIViewDetallePedidoTitleBar
        {
            get
            {
                if ((this.mUIViewDetallePedidoTitleBar == null))
                {
                    this.mUIViewDetallePedidoTitleBar = new WinTitleBar(this);
                    #region Criterio de búsqueda
                    this.mUIViewDetallePedidoTitleBar.WindowTitles.Add("ViewDetallePedido");
                    #endregion
                }
                return this.mUIViewDetallePedidoTitleBar;
            }
        }
        
        public UIEntertextWindow3 UIEntertextWindow
        {
            get
            {
                if ((this.mUIEntertextWindow == null))
                {
                    this.mUIEntertextWindow = new UIEntertextWindow3(this);
                }
                return this.mUIEntertextWindow;
            }
        }
        
        public UITxtcantidadWindow UITxtcantidadWindow
        {
            get
            {
                if ((this.mUITxtcantidadWindow == null))
                {
                    this.mUITxtcantidadWindow = new UITxtcantidadWindow(this);
                }
                return this.mUITxtcantidadWindow;
            }
        }
        
        public UIEntertextWindow11 UIEntertextWindow1
        {
            get
            {
                if ((this.mUIEntertextWindow1 == null))
                {
                    this.mUIEntertextWindow1 = new UIEntertextWindow11(this);
                }
                return this.mUIEntertextWindow1;
            }
        }
        
        public UIBtnBuscarWindow1 UIBtnBuscarWindow
        {
            get
            {
                if ((this.mUIBtnBuscarWindow == null))
                {
                    this.mUIBtnBuscarWindow = new UIBtnBuscarWindow1(this);
                }
                return this.mUIBtnBuscarWindow;
            }
        }
        
        public UIBtnAgregarWindow UIBtnAgregarWindow
        {
            get
            {
                if ((this.mUIBtnAgregarWindow == null))
                {
                    this.mUIBtnAgregarWindow = new UIBtnAgregarWindow(this);
                }
                return this.mUIBtnAgregarWindow;
            }
        }
        #endregion
        
        #region Fields
        private WinTitleBar mUIViewDetallePedidoTitleBar;
        
        private UIEntertextWindow3 mUIEntertextWindow;
        
        private UITxtcantidadWindow mUITxtcantidadWindow;
        
        private UIEntertextWindow11 mUIEntertextWindow1;
        
        private UIBtnBuscarWindow1 mUIBtnBuscarWindow;
        
        private UIBtnAgregarWindow mUIBtnAgregarWindow;
        #endregion
    }
    
    [GeneratedCode("Generador de pruebas de UI codificadas", "16.0.31306.167")]
    public class UIEntertextWindow3 : WinWindow
    {
        
        public UIEntertextWindow3(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Criterio de búsqueda
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "edit";
            this.SearchProperties[WinWindow.PropertyNames.Instance] = "7";
            this.WindowTitles.Add("ViewDetallePedido");
            #endregion
        }
        
        #region Properties
        public WinEdit UIEditEdit
        {
            get
            {
                if ((this.mUIEditEdit == null))
                {
                    this.mUIEditEdit = new WinEdit(this);
                    #region Criterio de búsqueda
                    this.mUIEditEdit.WindowTitles.Add("ViewDetallePedido");
                    #endregion
                }
                return this.mUIEditEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUIEditEdit;
        #endregion
    }
    
    [GeneratedCode("Generador de pruebas de UI codificadas", "16.0.31306.167")]
    public class UITxtcantidadWindow : WinWindow
    {
        
        public UITxtcantidadWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Criterio de búsqueda
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "txtcantidad";
            this.WindowTitles.Add("ViewDetallePedido");
            #endregion
        }
        
        #region Properties
        public WinWindow UIEntertextWindow
        {
            get
            {
                if ((this.mUIEntertextWindow == null))
                {
                    this.mUIEntertextWindow = new WinWindow(this);
                    #region Criterio de búsqueda
                    this.mUIEntertextWindow.SearchProperties[WinWindow.PropertyNames.Name] = "Enter text";
                    this.mUIEntertextWindow.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.EDIT", PropertyExpressionOperator.Contains));
                    this.mUIEntertextWindow.WindowTitles.Add("ViewDetallePedido");
                    #endregion
                }
                return this.mUIEntertextWindow;
            }
        }
        #endregion
        
        #region Fields
        private WinWindow mUIEntertextWindow;
        #endregion
    }
    
    [GeneratedCode("Generador de pruebas de UI codificadas", "16.0.31306.167")]
    public class UIEntertextWindow11 : WinWindow
    {
        
        public UIEntertextWindow11(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Criterio de búsqueda
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "edit";
            this.WindowTitles.Add("ViewDetallePedido");
            #endregion
        }
        
        #region Properties
        public WinEdit UIEditEdit
        {
            get
            {
                if ((this.mUIEditEdit == null))
                {
                    this.mUIEditEdit = new WinEdit(this);
                    #region Criterio de búsqueda
                    this.mUIEditEdit.WindowTitles.Add("ViewDetallePedido");
                    #endregion
                }
                return this.mUIEditEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUIEditEdit;
        #endregion
    }
    
    [GeneratedCode("Generador de pruebas de UI codificadas", "16.0.31306.167")]
    public class UIBtnBuscarWindow1 : WinWindow
    {
        
        public UIBtnBuscarWindow1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Criterio de búsqueda
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "btnBuscar";
            this.WindowTitles.Add("ViewDetallePedido");
            #endregion
        }
        
        #region Properties
        public WinClient UIBtnBuscarClient
        {
            get
            {
                if ((this.mUIBtnBuscarClient == null))
                {
                    this.mUIBtnBuscarClient = new WinClient(this);
                    #region Criterio de búsqueda
                    this.mUIBtnBuscarClient.WindowTitles.Add("ViewDetallePedido");
                    #endregion
                }
                return this.mUIBtnBuscarClient;
            }
        }
        #endregion
        
        #region Fields
        private WinClient mUIBtnBuscarClient;
        #endregion
    }
    
    [GeneratedCode("Generador de pruebas de UI codificadas", "16.0.31306.167")]
    public class UIBtnAgregarWindow : WinWindow
    {
        
        public UIBtnAgregarWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Criterio de búsqueda
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "btnAgregar";
            this.WindowTitles.Add("ViewDetallePedido");
            #endregion
        }
        
        #region Properties
        public WinClient UIAgregarClient
        {
            get
            {
                if ((this.mUIAgregarClient == null))
                {
                    this.mUIAgregarClient = new WinClient(this);
                    #region Criterio de búsqueda
                    this.mUIAgregarClient.SearchProperties[WinControl.PropertyNames.Name] = "Agregar ";
                    this.mUIAgregarClient.WindowTitles.Add("ViewDetallePedido");
                    #endregion
                }
                return this.mUIAgregarClient;
            }
        }
        #endregion
        
        #region Fields
        private WinClient mUIAgregarClient;
        #endregion
    }
    
    [GeneratedCode("Generador de pruebas de UI codificadas", "16.0.31306.167")]
    public class UIViewDetallePedidoWindow1 : WinWindow
    {
        
        public UIViewDetallePedidoWindow1()
        {
            #region Criterio de búsqueda
            this.SearchProperties[WinWindow.PropertyNames.Name] = "ViewDetallePedido";
            this.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.Window", PropertyExpressionOperator.Contains));
            this.FilterProperties[WinWindow.PropertyNames.OrderOfInvocation] = "2";
            this.WindowTitles.Add("ViewDetallePedido");
            #endregion
        }
        
        #region Properties
        public UIEntertextWindow4 UIEntertextWindow
        {
            get
            {
                if ((this.mUIEntertextWindow == null))
                {
                    this.mUIEntertextWindow = new UIEntertextWindow4(this);
                }
                return this.mUIEntertextWindow;
            }
        }
        
        public UIEntertextWindow12 UIEntertextWindow1
        {
            get
            {
                if ((this.mUIEntertextWindow1 == null))
                {
                    this.mUIEntertextWindow1 = new UIEntertextWindow12(this);
                }
                return this.mUIEntertextWindow1;
            }
        }
        
        public UIBtnBuscarWindow2 UIBtnBuscarWindow
        {
            get
            {
                if ((this.mUIBtnBuscarWindow == null))
                {
                    this.mUIBtnBuscarWindow = new UIBtnBuscarWindow2(this);
                }
                return this.mUIBtnBuscarWindow;
            }
        }
        
        public UIBtnAgregarWindow1 UIBtnAgregarWindow
        {
            get
            {
                if ((this.mUIBtnAgregarWindow == null))
                {
                    this.mUIBtnAgregarWindow = new UIBtnAgregarWindow1(this);
                }
                return this.mUIBtnAgregarWindow;
            }
        }
        #endregion
        
        #region Fields
        private UIEntertextWindow4 mUIEntertextWindow;
        
        private UIEntertextWindow12 mUIEntertextWindow1;
        
        private UIBtnBuscarWindow2 mUIBtnBuscarWindow;
        
        private UIBtnAgregarWindow1 mUIBtnAgregarWindow;
        #endregion
    }
    
    [GeneratedCode("Generador de pruebas de UI codificadas", "16.0.31306.167")]
    public class UIEntertextWindow4 : WinWindow
    {
        
        public UIEntertextWindow4(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Criterio de búsqueda
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "edit";
            this.SearchProperties[WinWindow.PropertyNames.Instance] = "7";
            this.WindowTitles.Add("ViewDetallePedido");
            #endregion
        }
        
        #region Properties
        public WinEdit UIEditEdit
        {
            get
            {
                if ((this.mUIEditEdit == null))
                {
                    this.mUIEditEdit = new WinEdit(this);
                    #region Criterio de búsqueda
                    this.mUIEditEdit.WindowTitles.Add("ViewDetallePedido");
                    #endregion
                }
                return this.mUIEditEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUIEditEdit;
        #endregion
    }
    
    [GeneratedCode("Generador de pruebas de UI codificadas", "16.0.31306.167")]
    public class UIEntertextWindow12 : WinWindow
    {
        
        public UIEntertextWindow12(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Criterio de búsqueda
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "edit";
            this.WindowTitles.Add("ViewDetallePedido");
            #endregion
        }
        
        #region Properties
        public WinEdit UIEditEdit
        {
            get
            {
                if ((this.mUIEditEdit == null))
                {
                    this.mUIEditEdit = new WinEdit(this);
                    #region Criterio de búsqueda
                    this.mUIEditEdit.WindowTitles.Add("ViewDetallePedido");
                    #endregion
                }
                return this.mUIEditEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUIEditEdit;
        #endregion
    }
    
    [GeneratedCode("Generador de pruebas de UI codificadas", "16.0.31306.167")]
    public class UIBtnBuscarWindow2 : WinWindow
    {
        
        public UIBtnBuscarWindow2(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Criterio de búsqueda
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "btnBuscar";
            this.WindowTitles.Add("ViewDetallePedido");
            #endregion
        }
        
        #region Properties
        public WinClient UIBtnBuscarClient
        {
            get
            {
                if ((this.mUIBtnBuscarClient == null))
                {
                    this.mUIBtnBuscarClient = new WinClient(this);
                    #region Criterio de búsqueda
                    this.mUIBtnBuscarClient.WindowTitles.Add("ViewDetallePedido");
                    #endregion
                }
                return this.mUIBtnBuscarClient;
            }
        }
        #endregion
        
        #region Fields
        private WinClient mUIBtnBuscarClient;
        #endregion
    }
    
    [GeneratedCode("Generador de pruebas de UI codificadas", "16.0.31306.167")]
    public class UIBtnAgregarWindow1 : WinWindow
    {
        
        public UIBtnAgregarWindow1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Criterio de búsqueda
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "btnAgregar";
            this.WindowTitles.Add("ViewDetallePedido");
            #endregion
        }
        
        #region Properties
        public WinClient UIAgregarClient
        {
            get
            {
                if ((this.mUIAgregarClient == null))
                {
                    this.mUIAgregarClient = new WinClient(this);
                    #region Criterio de búsqueda
                    this.mUIAgregarClient.SearchProperties[WinControl.PropertyNames.Name] = "Agregar ";
                    this.mUIAgregarClient.WindowTitles.Add("ViewDetallePedido");
                    #endregion
                }
                return this.mUIAgregarClient;
            }
        }
        #endregion
        
        #region Fields
        private WinClient mUIAgregarClient;
        #endregion
    }
}
