// ------------------------------------------------------------------------------
//  <auto-generated>
//      Este código lo generó el generador de pruebas automatizadas de IU.
//      Versión: 16.0.0.0
//
//      Los cambios realizados en este archivo pueden provocar un comportamiento incorrecto y se perderán si
//      se vuelve a generar el código.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace CodedUITest_Gestion_Pedido
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.WinControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Generador de pruebas de UI codificadas", "16.0.31306.167")]
    public partial class UIMap
    {
        
        /// <summary>
        /// Listar CLientes , Registrar Cliente , Actualizar Cliente
        /// </summary>
        public void Recorded_GestionCliente()
        {
            #region Variable Declarations
            WinEdit uIEditEdit = this.UIViewLogWindow.UIEntertextWindow.UIEditEdit;
            WinEdit uIEditEdit1 = this.UIViewLogWindow.UIEntertextWindow1.UIEditEdit;
            WinClient uIIniciarSesionClient = this.UIViewLogWindow.UIBtnIniciarSesionWindow.UIIniciarSesionClient;
            WinControl uIItemDialog = this.UIItemWindow.UIItemWindow1.UIItemDialog;
            WinButton uIOKButton = this.UIOKWindow.UIOKButton;
            WinWindow uIGestionClientesWindow = this.UIViewPrincipalWindow.UIGestionClientesClient.UIGestionClientesWindow;
            WinClient uIBtnBuscarClient = this.UIViewPrincipalWindow.UIBtnBuscarWindow.UIBtnBuscarClient;
            WinEdit uIEditEdit2 = this.UIViewPrincipalWindow.UIEntertextWindow.UIEditEdit;
            WinClient uIBtnRegistrarClient = this.UIViewPrincipalWindow.UIBtnRegistrarWindow.UIBtnRegistrarClient;
            WinEdit uIEditEdit3 = this.UIViewRegistroClienteWindow.UIEntertextWindow.UIEditEdit;
            WinEdit uIEditEdit4 = this.UIViewRegistroClienteWindow.UIEntertextWindow1.UIEditEdit;
            WinEdit uIEditEdit5 = this.UIViewRegistroClienteWindow.UIEntertextWindow2.UIEditEdit;
            WinClient uIViewRegistroClienteClient = this.UIViewRegistroClienteWindow.UIViewRegistroClienteClient;
            WinEdit uIEditEdit6 = this.UIViewRegistroClienteWindow.UIEntertextWindow3.UIEditEdit;
            WinClient uITxtGmailClient = this.UIViewRegistroClienteWindow.UITxtGmailWindow.UITxtGmailClient;
            WinEdit uIEditEdit7 = this.UIViewRegistroClienteWindow.UIEntertextWindow4.UIEditEdit;
            WinEdit uIEditEdit8 = this.UIViewRegistroClienteWindow.UIEntertextWindow5.UIEditEdit;
            WinEdit uIEditEdit9 = this.UIViewRegistroClienteWindow.UIEntertextWindow6.UIEditEdit;
            WinText uIRegistrarText = this.UIViewRegistroClienteWindow.UIRegistrarWindow.UIRegistrarText;
            WinButton uIOKButton1 = this.UIConfirmacionWindow.UIOKWindow.UIOKButton;
            WinWindow uIEntertextWindow = this.UIViewPrincipalWindow.UITxtBuscarWindow.UIEntertextWindow;
            WinCell uIJhonatanCell = this.UIViewPrincipalWindow.UIDgvClientesWindow.UIDataGridViewTable.UIRow0Row.UIJhonatanCell;
            WinClient uIBtnActualizarClient = this.UIViewPrincipalWindow.UIBtnActualizarWindow.UIBtnActualizarClient;
            WinEdit uIEditEdit10 = this.UIViewActualizarClientWindow.UIEntertextWindow.UIEditEdit;
            WinEdit uIEditEdit11 = this.UIViewActualizarClientWindow.UIEntertextWindow1.UIEditEdit;
            WinClient uIActualizarClient = this.UIViewActualizarClientWindow.UIBtnActualizarWindow.UIActualizarClient;
            WinButton uICloseButton = this.UIViewPrincipalWindow.UIViewPrincipalTitleBar.UICloseButton;
            #endregion

            // Iniciar '%USERPROFILE%\Downloads\DDD (1)\DDD\UI.Desktop\bin\Debug\UI.Desktop.exe'
            ApplicationUnderTest uIViewLogWindow = ApplicationUnderTest.Launch(this.Recorded_GestionClienteParams.UIViewLogWindowExePath, this.Recorded_GestionClienteParams.UIViewLogWindowAlternateExePath);

            // Escribir 'Admin' en cuadro de texto 'edit'
            uIEditEdit.Text = this.Recorded_GestionClienteParams.UIEditEditText;

            // Escribir '123qweu0' en cuadro de texto 'edit'
            uIEditEdit1.Text = this.Recorded_GestionClienteParams.UIEditEditText1;

            // Clic 'Iniciar Sesion' cliente
            Mouse.Click(uIIniciarSesionClient, new Point(35, 9));

            // Clic Dialog
            Mouse.Click(uIItemDialog, new Point(71, 67));

            // Clic 'OK' botón
            Mouse.Click(uIOKButton, new Point(48, 3));

            // Clic 'Gestion Clientes' ventana
            Mouse.Click(uIGestionClientesWindow, new Point(92, 5));

            // Clic 'btnBuscar' cliente
            Mouse.Click(uIBtnBuscarClient, new Point(13, 10));

            // Clic 'btnBuscar' cliente
            Mouse.Click(uIBtnBuscarClient, new Point(19, 18));

            // Escribir '83076' en cuadro de texto 'edit'
            uIEditEdit2.Text = this.Recorded_GestionClienteParams.UIEditEditText2;

            // Clic 'btnBuscar' cliente
            Mouse.Click(uIBtnBuscarClient, new Point(21, 12));

            // Clic 'btnRegistrar' cliente
            Mouse.Click(uIBtnRegistrarClient, new Point(8, 22));

            // Escribir '743940' en cuadro de texto 'edit'
            uIEditEdit3.Text = this.Recorded_GestionClienteParams.UIEditEditText3;

            // Escribir 'Jhonatan' en cuadro de texto 'edit'
            uIEditEdit4.Text = this.Recorded_GestionClienteParams.UIEditEditText4;

            // Escribir 'Mamani Ramos' en cuadro de texto 'edit'
            uIEditEdit5.Text = this.Recorded_GestionClienteParams.UIEditEditText5;

            // Clic 'ViewRegistroCliente' cliente
            Mouse.Click(uIViewRegistroClienteClient, new Point(214, 244));

            // Escribir 'Tacna' en cuadro de texto 'edit'
            uIEditEdit6.Text = this.Recorded_GestionClienteParams.UIEditEditText6;

            // Doble clic 'txtGmail' cliente
            Mouse.DoubleClick(uITxtGmailClient, new Point(50, 8));

            // Escribir 'Stveve' en cuadro de texto 'edit'
            uIEditEdit7.Text = this.Recorded_GestionClienteParams.UIEditEditText7;

            // Escribir '930123451' en cuadro de texto 'edit'
            uIEditEdit8.Text = this.Recorded_GestionClienteParams.UIEditEditText8;

            // Clic 'edit' cuadro de texto
            Mouse.Click(uIEditEdit9, new Point(33, 1));

            // Escribir '********' en cuadro de texto 'edit'
            Keyboard.SendKeys(uIEditEdit9, this.Recorded_GestionClienteParams.UIEditEditSendKeys, true);

            // Clic 'Registrar' etiqueta
            Mouse.Click(uIRegistrarText, new Point(12, 11));

            // Clic 'OK' botón
            Mouse.Click(uIOKButton1, new Point(38, 8));

            // Escribir '74394048' en cuadro de texto 'edit'
            uIEditEdit2.Text = this.Recorded_GestionClienteParams.UIEditEditText9;

            // Clic 'btnBuscar' cliente
            Mouse.Click(uIBtnBuscarClient, new Point(14, 17));

            // Clic 'OK' botón
            Mouse.Click(uIOKButton, new Point(31, 8));

            // Clic 'Enter text' ventana
            Mouse.Click(uIEntertextWindow, new Point(134, -1));

            // Escribir '743940' en cuadro de texto 'edit'
            uIEditEdit2.Text = this.Recorded_GestionClienteParams.UIEditEditText10;

            // Clic 'btnBuscar' cliente
            Mouse.Click(uIBtnBuscarClient, new Point(23, 24));

            // Doble clic 'Jhonatan' celda
            Mouse.DoubleClick(uIJhonatanCell, new Point(8, 20));

            // Clic 'btnActualizar' cliente
            Mouse.Click(uIBtnActualizarClient, new Point(14, 9));

            // Escribir 'Stveve02' en cuadro de texto 'edit'
            uIEditEdit10.Text = this.Recorded_GestionClienteParams.UIEditEditText11;

            // Escribir '949726280' en cuadro de texto 'edit'
            uIEditEdit11.Text = this.Recorded_GestionClienteParams.UIEditEditText12;

            // Clic 'Actualizar' cliente
            Mouse.Click(uIActualizarClient, new Point(34, 27));

            // Clic 'OK' botón
            Mouse.Click(uIOKButton1, new Point(29, 17));

            // Clic 'btnBuscar' cliente
            Mouse.Click(uIBtnBuscarClient, new Point(12, 15));

            // Clic 'Close' botón
            Mouse.Click(uICloseButton, new Point(31, 10));
        }
        
        #region Properties
        public virtual Recorded_GestionClienteParams Recorded_GestionClienteParams
        {
            get
            {
                if ((this.mRecorded_GestionClienteParams == null))
                {
                    this.mRecorded_GestionClienteParams = new Recorded_GestionClienteParams();
                }
                return this.mRecorded_GestionClienteParams;
            }
        }
        
        public UIViewLogWindow UIViewLogWindow
        {
            get
            {
                if ((this.mUIViewLogWindow == null))
                {
                    this.mUIViewLogWindow = new UIViewLogWindow();
                }
                return this.mUIViewLogWindow;
            }
        }
        
        public UIItemWindow UIItemWindow
        {
            get
            {
                if ((this.mUIItemWindow == null))
                {
                    this.mUIItemWindow = new UIItemWindow();
                }
                return this.mUIItemWindow;
            }
        }
        
        public UIOKWindow UIOKWindow
        {
            get
            {
                if ((this.mUIOKWindow == null))
                {
                    this.mUIOKWindow = new UIOKWindow();
                }
                return this.mUIOKWindow;
            }
        }
        
        public UIViewPrincipalWindow UIViewPrincipalWindow
        {
            get
            {
                if ((this.mUIViewPrincipalWindow == null))
                {
                    this.mUIViewPrincipalWindow = new UIViewPrincipalWindow();
                }
                return this.mUIViewPrincipalWindow;
            }
        }
        
        public UIViewRegistroClienteWindow UIViewRegistroClienteWindow
        {
            get
            {
                if ((this.mUIViewRegistroClienteWindow == null))
                {
                    this.mUIViewRegistroClienteWindow = new UIViewRegistroClienteWindow();
                }
                return this.mUIViewRegistroClienteWindow;
            }
        }
        
        public UIConfirmacionWindow UIConfirmacionWindow
        {
            get
            {
                if ((this.mUIConfirmacionWindow == null))
                {
                    this.mUIConfirmacionWindow = new UIConfirmacionWindow();
                }
                return this.mUIConfirmacionWindow;
            }
        }
        
        public UIViewActualizarClientWindow UIViewActualizarClientWindow
        {
            get
            {
                if ((this.mUIViewActualizarClientWindow == null))
                {
                    this.mUIViewActualizarClientWindow = new UIViewActualizarClientWindow();
                }
                return this.mUIViewActualizarClientWindow;
            }
        }
        #endregion
        
        #region Fields
        private Recorded_GestionClienteParams mRecorded_GestionClienteParams;
        
        private UIViewLogWindow mUIViewLogWindow;
        
        private UIItemWindow mUIItemWindow;
        
        private UIOKWindow mUIOKWindow;
        
        private UIViewPrincipalWindow mUIViewPrincipalWindow;
        
        private UIViewRegistroClienteWindow mUIViewRegistroClienteWindow;
        
        private UIConfirmacionWindow mUIConfirmacionWindow;
        
        private UIViewActualizarClientWindow mUIViewActualizarClientWindow;
        #endregion
    }
    
    /// <summary>
    /// Parámetros que se van a pasar a 'Recorded_GestionCliente'
    /// </summary>
    [GeneratedCode("Generador de pruebas de UI codificadas", "16.0.31306.167")]
    public class Recorded_GestionClienteParams
    {
        
        #region Fields
        /// <summary>
        /// Iniciar '%USERPROFILE%\Downloads\DDD (1)\DDD\UI.Desktop\bin\Debug\UI.Desktop.exe'
        /// </summary>
        public string UIViewLogWindowExePath = "C:\\Users\\USUARIO\\Downloads\\DDD (1)\\DDD\\UI.Desktop\\bin\\Debug\\UI.Desktop.exe";
        
        /// <summary>
        /// Iniciar '%USERPROFILE%\Downloads\DDD (1)\DDD\UI.Desktop\bin\Debug\UI.Desktop.exe'
        /// </summary>
        public string UIViewLogWindowAlternateExePath = "%USERPROFILE%\\Downloads\\DDD (1)\\DDD\\UI.Desktop\\bin\\Debug\\UI.Desktop.exe";
        
        /// <summary>
        /// Escribir 'Admin' en cuadro de texto 'edit'
        /// </summary>
        public string UIEditEditText = "Admin";
        
        /// <summary>
        /// Escribir '123qweu0' en cuadro de texto 'edit'
        /// </summary>
        public string UIEditEditText1 = "123qweu0";
        
        /// <summary>
        /// Escribir '83076' en cuadro de texto 'edit'
        /// </summary>
        public string UIEditEditText2 = "83076";
        
        /// <summary>
        /// Escribir '743940' en cuadro de texto 'edit'
        /// </summary>
        public string UIEditEditText3 = "743940";
        
        /// <summary>
        /// Escribir 'Jhonatan' en cuadro de texto 'edit'
        /// </summary>
        public string UIEditEditText4 = "Jhonatan";
        
        /// <summary>
        /// Escribir 'Mamani Ramos' en cuadro de texto 'edit'
        /// </summary>
        public string UIEditEditText5 = "Mamani Ramos";
        
        /// <summary>
        /// Escribir 'Tacna' en cuadro de texto 'edit'
        /// </summary>
        public string UIEditEditText6 = "Tacna";
        
        /// <summary>
        /// Escribir 'Stveve' en cuadro de texto 'edit'
        /// </summary>
        public string UIEditEditText7 = "Stveve";
        
        /// <summary>
        /// Escribir '930123451' en cuadro de texto 'edit'
        /// </summary>
        public string UIEditEditText8 = "930123451";
        
        /// <summary>
        /// Escribir '********' en cuadro de texto 'edit'
        /// </summary>
        public string UIEditEditSendKeys = "OEZwzoizO3v4qv/x4I2/IIpUENTAN4g+R3DbkP82Gbz9/tTbkUv/98PsafdsQpAY";
        
        /// <summary>
        /// Escribir '74394048' en cuadro de texto 'edit'
        /// </summary>
        public string UIEditEditText9 = "74394048";
        
        /// <summary>
        /// Escribir '743940' en cuadro de texto 'edit'
        /// </summary>
        public string UIEditEditText10 = "743940";
        
        /// <summary>
        /// Escribir 'Stveve02' en cuadro de texto 'edit'
        /// </summary>
        public string UIEditEditText11 = "Stveve02";
        
        /// <summary>
        /// Escribir '949726280' en cuadro de texto 'edit'
        /// </summary>
        public string UIEditEditText12 = "949726280";
        #endregion
    }
    
    [GeneratedCode("Generador de pruebas de UI codificadas", "16.0.31306.167")]
    public class UIViewLogWindow : WinWindow
    {
        
        public UIViewLogWindow()
        {
            #region Criterio de búsqueda
            this.SearchProperties[WinWindow.PropertyNames.Name] = "ViewLog";
            this.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.Window", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("ViewLog");
            #endregion
        }
        
        #region Properties
        public UIEntertextWindow UIEntertextWindow
        {
            get
            {
                if ((this.mUIEntertextWindow == null))
                {
                    this.mUIEntertextWindow = new UIEntertextWindow(this);
                }
                return this.mUIEntertextWindow;
            }
        }
        
        public UIEntertextWindow1 UIEntertextWindow1
        {
            get
            {
                if ((this.mUIEntertextWindow1 == null))
                {
                    this.mUIEntertextWindow1 = new UIEntertextWindow1(this);
                }
                return this.mUIEntertextWindow1;
            }
        }
        
        public UIBtnIniciarSesionWindow UIBtnIniciarSesionWindow
        {
            get
            {
                if ((this.mUIBtnIniciarSesionWindow == null))
                {
                    this.mUIBtnIniciarSesionWindow = new UIBtnIniciarSesionWindow(this);
                }
                return this.mUIBtnIniciarSesionWindow;
            }
        }
        #endregion
        
        #region Fields
        private UIEntertextWindow mUIEntertextWindow;
        
        private UIEntertextWindow1 mUIEntertextWindow1;
        
        private UIBtnIniciarSesionWindow mUIBtnIniciarSesionWindow;
        #endregion
    }
    
    [GeneratedCode("Generador de pruebas de UI codificadas", "16.0.31306.167")]
    public class UIEntertextWindow : WinWindow
    {
        
        public UIEntertextWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Criterio de búsqueda
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "edit";
            this.SearchProperties[WinWindow.PropertyNames.Instance] = "2";
            this.WindowTitles.Add("ViewLog");
            #endregion
        }
        
        #region Properties
        public WinEdit UIEditEdit
        {
            get
            {
                if ((this.mUIEditEdit == null))
                {
                    this.mUIEditEdit = new WinEdit(this);
                    #region Criterio de búsqueda
                    this.mUIEditEdit.WindowTitles.Add("ViewLog");
                    #endregion
                }
                return this.mUIEditEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUIEditEdit;
        #endregion
    }
    
    [GeneratedCode("Generador de pruebas de UI codificadas", "16.0.31306.167")]
    public class UIEntertextWindow1 : WinWindow
    {
        
        public UIEntertextWindow1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Criterio de búsqueda
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "edit";
            this.WindowTitles.Add("ViewLog");
            #endregion
        }
        
        #region Properties
        public WinEdit UIEditEdit
        {
            get
            {
                if ((this.mUIEditEdit == null))
                {
                    this.mUIEditEdit = new WinEdit(this);
                    #region Criterio de búsqueda
                    this.mUIEditEdit.WindowTitles.Add("ViewLog");
                    #endregion
                }
                return this.mUIEditEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUIEditEdit;
        #endregion
    }
    
    [GeneratedCode("Generador de pruebas de UI codificadas", "16.0.31306.167")]
    public class UIBtnIniciarSesionWindow : WinWindow
    {
        
        public UIBtnIniciarSesionWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Criterio de búsqueda
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "btnIniciarSesion";
            this.WindowTitles.Add("ViewLog");
            #endregion
        }
        
        #region Properties
        public WinClient UIIniciarSesionClient
        {
            get
            {
                if ((this.mUIIniciarSesionClient == null))
                {
                    this.mUIIniciarSesionClient = new WinClient(this);
                    #region Criterio de búsqueda
                    this.mUIIniciarSesionClient.SearchProperties[WinControl.PropertyNames.Name] = "Iniciar Sesion";
                    this.mUIIniciarSesionClient.WindowTitles.Add("ViewLog");
                    #endregion
                }
                return this.mUIIniciarSesionClient;
            }
        }
        #endregion
        
        #region Fields
        private WinClient mUIIniciarSesionClient;
        #endregion
    }
    
    [GeneratedCode("Generador de pruebas de UI codificadas", "16.0.31306.167")]
    public class UIItemWindow : WinWindow
    {
        
        public UIItemWindow()
        {
            #region Criterio de búsqueda
            this.SearchProperties[WinWindow.PropertyNames.AccessibleName] = "Desktop 1";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "#32769";
            #endregion
        }
        
        #region Properties
        public UIItemWindow1 UIItemWindow1
        {
            get
            {
                if ((this.mUIItemWindow1 == null))
                {
                    this.mUIItemWindow1 = new UIItemWindow1(this);
                }
                return this.mUIItemWindow1;
            }
        }
        #endregion
        
        #region Fields
        private UIItemWindow1 mUIItemWindow1;
        #endregion
    }
    
    [GeneratedCode("Generador de pruebas de UI codificadas", "16.0.31306.167")]
    public class UIItemWindow1 : WinWindow
    {
        
        public UIItemWindow1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Criterio de búsqueda
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "#32770";
            #endregion
        }
        
        #region Properties
        public WinControl UIItemDialog
        {
            get
            {
                if ((this.mUIItemDialog == null))
                {
                    this.mUIItemDialog = new WinControl(this);
                    #region Criterio de búsqueda
                    this.mUIItemDialog.SearchProperties[UITestControl.PropertyNames.ControlType] = "Dialog";
                    #endregion
                }
                return this.mUIItemDialog;
            }
        }
        #endregion
        
        #region Fields
        private WinControl mUIItemDialog;
        #endregion
    }
    
    [GeneratedCode("Generador de pruebas de UI codificadas", "16.0.31306.167")]
    public class UIOKWindow : WinWindow
    {
        
        public UIOKWindow()
        {
            #region Criterio de búsqueda
            this.SearchProperties[WinWindow.PropertyNames.Name] = "OK";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "Button";
            this.WindowTitles.Add("OK");
            #endregion
        }
        
        #region Properties
        public WinButton UIOKButton
        {
            get
            {
                if ((this.mUIOKButton == null))
                {
                    this.mUIOKButton = new WinButton(this);
                    #region Criterio de búsqueda
                    this.mUIOKButton.SearchProperties[WinButton.PropertyNames.Name] = "OK";
                    this.mUIOKButton.WindowTitles.Add("OK");
                    #endregion
                }
                return this.mUIOKButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIOKButton;
        #endregion
    }
    
    [GeneratedCode("Generador de pruebas de UI codificadas", "16.0.31306.167")]
    public class UIViewPrincipalWindow : WinWindow
    {
        
        public UIViewPrincipalWindow()
        {
            #region Criterio de búsqueda
            this.SearchProperties[WinWindow.PropertyNames.Name] = "ViewPrincipal";
            this.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.Window", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("ViewPrincipal");
            #endregion
        }
        
        #region Properties
        public UIGestionClientesClient UIGestionClientesClient
        {
            get
            {
                if ((this.mUIGestionClientesClient == null))
                {
                    this.mUIGestionClientesClient = new UIGestionClientesClient(this);
                }
                return this.mUIGestionClientesClient;
            }
        }
        
        public UIBtnBuscarWindow UIBtnBuscarWindow
        {
            get
            {
                if ((this.mUIBtnBuscarWindow == null))
                {
                    this.mUIBtnBuscarWindow = new UIBtnBuscarWindow(this);
                }
                return this.mUIBtnBuscarWindow;
            }
        }
        
        public UIEntertextWindow2 UIEntertextWindow
        {
            get
            {
                if ((this.mUIEntertextWindow == null))
                {
                    this.mUIEntertextWindow = new UIEntertextWindow2(this);
                }
                return this.mUIEntertextWindow;
            }
        }
        
        public UIBtnRegistrarWindow UIBtnRegistrarWindow
        {
            get
            {
                if ((this.mUIBtnRegistrarWindow == null))
                {
                    this.mUIBtnRegistrarWindow = new UIBtnRegistrarWindow(this);
                }
                return this.mUIBtnRegistrarWindow;
            }
        }
        
        public UITxtBuscarWindow UITxtBuscarWindow
        {
            get
            {
                if ((this.mUITxtBuscarWindow == null))
                {
                    this.mUITxtBuscarWindow = new UITxtBuscarWindow(this);
                }
                return this.mUITxtBuscarWindow;
            }
        }
        
        public UIDgvClientesWindow UIDgvClientesWindow
        {
            get
            {
                if ((this.mUIDgvClientesWindow == null))
                {
                    this.mUIDgvClientesWindow = new UIDgvClientesWindow(this);
                }
                return this.mUIDgvClientesWindow;
            }
        }
        
        public UIBtnActualizarWindow UIBtnActualizarWindow
        {
            get
            {
                if ((this.mUIBtnActualizarWindow == null))
                {
                    this.mUIBtnActualizarWindow = new UIBtnActualizarWindow(this);
                }
                return this.mUIBtnActualizarWindow;
            }
        }
        
        public UIViewPrincipalTitleBar UIViewPrincipalTitleBar
        {
            get
            {
                if ((this.mUIViewPrincipalTitleBar == null))
                {
                    this.mUIViewPrincipalTitleBar = new UIViewPrincipalTitleBar(this);
                }
                return this.mUIViewPrincipalTitleBar;
            }
        }
        #endregion
        
        #region Fields
        private UIGestionClientesClient mUIGestionClientesClient;
        
        private UIBtnBuscarWindow mUIBtnBuscarWindow;
        
        private UIEntertextWindow2 mUIEntertextWindow;
        
        private UIBtnRegistrarWindow mUIBtnRegistrarWindow;
        
        private UITxtBuscarWindow mUITxtBuscarWindow;
        
        private UIDgvClientesWindow mUIDgvClientesWindow;
        
        private UIBtnActualizarWindow mUIBtnActualizarWindow;
        
        private UIViewPrincipalTitleBar mUIViewPrincipalTitleBar;
        #endregion
    }
    
    [GeneratedCode("Generador de pruebas de UI codificadas", "16.0.31306.167")]
    public class UIGestionClientesClient : WinClient
    {
        
        public UIGestionClientesClient(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Criterio de búsqueda
            this.SearchProperties[WinControl.PropertyNames.Name] = "Gestion Clientes";
            this.WindowTitles.Add("ViewPrincipal");
            #endregion
        }
        
        #region Properties
        public WinWindow UIGestionClientesWindow
        {
            get
            {
                if ((this.mUIGestionClientesWindow == null))
                {
                    this.mUIGestionClientesWindow = new WinWindow(this);
                    #region Criterio de búsqueda
                    this.mUIGestionClientesWindow.SearchProperties[WinWindow.PropertyNames.Name] = "Gestion Clientes";
                    this.mUIGestionClientesWindow.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.STATIC", PropertyExpressionOperator.Contains));
                    this.mUIGestionClientesWindow.WindowTitles.Add("ViewPrincipal");
                    #endregion
                }
                return this.mUIGestionClientesWindow;
            }
        }
        #endregion
        
        #region Fields
        private WinWindow mUIGestionClientesWindow;
        #endregion
    }
    
    [GeneratedCode("Generador de pruebas de UI codificadas", "16.0.31306.167")]
    public class UIBtnBuscarWindow : WinWindow
    {
        
        public UIBtnBuscarWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Criterio de búsqueda
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "btnBuscar";
            this.WindowTitles.Add("ViewPrincipal");
            #endregion
        }
        
        #region Properties
        public WinClient UIBtnBuscarClient
        {
            get
            {
                if ((this.mUIBtnBuscarClient == null))
                {
                    this.mUIBtnBuscarClient = new WinClient(this);
                    #region Criterio de búsqueda
                    this.mUIBtnBuscarClient.WindowTitles.Add("ViewPrincipal");
                    #endregion
                }
                return this.mUIBtnBuscarClient;
            }
        }
        #endregion
        
        #region Fields
        private WinClient mUIBtnBuscarClient;
        #endregion
    }
    
    [GeneratedCode("Generador de pruebas de UI codificadas", "16.0.31306.167")]
    public class UIEntertextWindow2 : WinWindow
    {
        
        public UIEntertextWindow2(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Criterio de búsqueda
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "edit";
            this.WindowTitles.Add("ViewPrincipal");
            #endregion
        }
        
        #region Properties
        public WinEdit UIEditEdit
        {
            get
            {
                if ((this.mUIEditEdit == null))
                {
                    this.mUIEditEdit = new WinEdit(this);
                    #region Criterio de búsqueda
                    this.mUIEditEdit.WindowTitles.Add("ViewPrincipal");
                    #endregion
                }
                return this.mUIEditEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUIEditEdit;
        #endregion
    }
    
    [GeneratedCode("Generador de pruebas de UI codificadas", "16.0.31306.167")]
    public class UIBtnRegistrarWindow : WinWindow
    {
        
        public UIBtnRegistrarWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Criterio de búsqueda
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "btnRegistrar";
            this.WindowTitles.Add("ViewPrincipal");
            #endregion
        }
        
        #region Properties
        public WinClient UIBtnRegistrarClient
        {
            get
            {
                if ((this.mUIBtnRegistrarClient == null))
                {
                    this.mUIBtnRegistrarClient = new WinClient(this);
                    #region Criterio de búsqueda
                    this.mUIBtnRegistrarClient.WindowTitles.Add("ViewPrincipal");
                    #endregion
                }
                return this.mUIBtnRegistrarClient;
            }
        }
        #endregion
        
        #region Fields
        private WinClient mUIBtnRegistrarClient;
        #endregion
    }
    
    [GeneratedCode("Generador de pruebas de UI codificadas", "16.0.31306.167")]
    public class UITxtBuscarWindow : WinWindow
    {
        
        public UITxtBuscarWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Criterio de búsqueda
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "txtBuscar";
            this.WindowTitles.Add("ViewPrincipal");
            #endregion
        }
        
        #region Properties
        public WinWindow UIEntertextWindow
        {
            get
            {
                if ((this.mUIEntertextWindow == null))
                {
                    this.mUIEntertextWindow = new WinWindow(this);
                    #region Criterio de búsqueda
                    this.mUIEntertextWindow.SearchProperties[WinWindow.PropertyNames.Name] = "Enter text";
                    this.mUIEntertextWindow.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.EDIT", PropertyExpressionOperator.Contains));
                    this.mUIEntertextWindow.WindowTitles.Add("ViewPrincipal");
                    #endregion
                }
                return this.mUIEntertextWindow;
            }
        }
        #endregion
        
        #region Fields
        private WinWindow mUIEntertextWindow;
        #endregion
    }
    
    [GeneratedCode("Generador de pruebas de UI codificadas", "16.0.31306.167")]
    public class UIDgvClientesWindow : WinWindow
    {
        
        public UIDgvClientesWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Criterio de búsqueda
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "dgvClientes";
            this.WindowTitles.Add("ViewPrincipal");
            #endregion
        }
        
        #region Properties
        public UIDataGridViewTable UIDataGridViewTable
        {
            get
            {
                if ((this.mUIDataGridViewTable == null))
                {
                    this.mUIDataGridViewTable = new UIDataGridViewTable(this);
                }
                return this.mUIDataGridViewTable;
            }
        }
        #endregion
        
        #region Fields
        private UIDataGridViewTable mUIDataGridViewTable;
        #endregion
    }
    
    [GeneratedCode("Generador de pruebas de UI codificadas", "16.0.31306.167")]
    public class UIDataGridViewTable : WinTable
    {
        
        public UIDataGridViewTable(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Criterio de búsqueda
            this.SearchProperties[WinTable.PropertyNames.Name] = "DataGridView";
            this.WindowTitles.Add("ViewPrincipal");
            #endregion
        }
        
        #region Properties
        public UIRow0Row UIRow0Row
        {
            get
            {
                if ((this.mUIRow0Row == null))
                {
                    this.mUIRow0Row = new UIRow0Row(this);
                }
                return this.mUIRow0Row;
            }
        }
        #endregion
        
        #region Fields
        private UIRow0Row mUIRow0Row;
        #endregion
    }
    
    [GeneratedCode("Generador de pruebas de UI codificadas", "16.0.31306.167")]
    public class UIRow0Row : WinRow
    {
        
        public UIRow0Row(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Criterio de búsqueda
            this.SearchProperties.Add(new PropertyExpression(WinRow.PropertyNames.Value, ";743940;Jhonatan;Tacna;Mamani Ramos;930123451;Stveve", PropertyExpressionOperator.Contains));
            this.SearchConfigurations.Add(SearchConfiguration.AlwaysSearch);
            this.WindowTitles.Add("ViewPrincipal");
            #endregion
        }
        
        #region Properties
        public WinCell UIJhonatanCell
        {
            get
            {
                if ((this.mUIJhonatanCell == null))
                {
                    this.mUIJhonatanCell = new WinCell(this);
                    #region Criterio de búsqueda
                    this.mUIJhonatanCell.SearchProperties[WinCell.PropertyNames.Value] = "Jhonatan";
                    this.mUIJhonatanCell.WindowTitles.Add("ViewPrincipal");
                    #endregion
                }
                return this.mUIJhonatanCell;
            }
        }
        #endregion
        
        #region Fields
        private WinCell mUIJhonatanCell;
        #endregion
    }
    
    [GeneratedCode("Generador de pruebas de UI codificadas", "16.0.31306.167")]
    public class UIBtnActualizarWindow : WinWindow
    {
        
        public UIBtnActualizarWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Criterio de búsqueda
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "btnActualizar";
            this.WindowTitles.Add("ViewPrincipal");
            #endregion
        }
        
        #region Properties
        public WinClient UIBtnActualizarClient
        {
            get
            {
                if ((this.mUIBtnActualizarClient == null))
                {
                    this.mUIBtnActualizarClient = new WinClient(this);
                    #region Criterio de búsqueda
                    this.mUIBtnActualizarClient.WindowTitles.Add("ViewPrincipal");
                    #endregion
                }
                return this.mUIBtnActualizarClient;
            }
        }
        #endregion
        
        #region Fields
        private WinClient mUIBtnActualizarClient;
        #endregion
    }
    
    [GeneratedCode("Generador de pruebas de UI codificadas", "16.0.31306.167")]
    public class UIViewPrincipalTitleBar : WinTitleBar
    {
        
        public UIViewPrincipalTitleBar(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Criterio de búsqueda
            this.WindowTitles.Add("ViewPrincipal");
            #endregion
        }
        
        #region Properties
        public WinButton UICloseButton
        {
            get
            {
                if ((this.mUICloseButton == null))
                {
                    this.mUICloseButton = new WinButton(this);
                    #region Criterio de búsqueda
                    this.mUICloseButton.SearchProperties[WinButton.PropertyNames.Name] = "Close";
                    this.mUICloseButton.WindowTitles.Add("ViewPrincipal");
                    #endregion
                }
                return this.mUICloseButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUICloseButton;
        #endregion
    }
    
    [GeneratedCode("Generador de pruebas de UI codificadas", "16.0.31306.167")]
    public class UIViewRegistroClienteWindow : WinWindow
    {
        
        public UIViewRegistroClienteWindow()
        {
            #region Criterio de búsqueda
            this.SearchProperties[WinWindow.PropertyNames.Name] = "ViewRegistroCliente";
            this.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.Window", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("ViewRegistroCliente");
            #endregion
        }
        
        #region Properties
        public UIEntertextWindow3 UIEntertextWindow
        {
            get
            {
                if ((this.mUIEntertextWindow == null))
                {
                    this.mUIEntertextWindow = new UIEntertextWindow3(this);
                }
                return this.mUIEntertextWindow;
            }
        }
        
        public UIEntertextWindow11 UIEntertextWindow1
        {
            get
            {
                if ((this.mUIEntertextWindow1 == null))
                {
                    this.mUIEntertextWindow1 = new UIEntertextWindow11(this);
                }
                return this.mUIEntertextWindow1;
            }
        }
        
        public UIEntertextWindow21 UIEntertextWindow2
        {
            get
            {
                if ((this.mUIEntertextWindow2 == null))
                {
                    this.mUIEntertextWindow2 = new UIEntertextWindow21(this);
                }
                return this.mUIEntertextWindow2;
            }
        }
        
        public WinClient UIViewRegistroClienteClient
        {
            get
            {
                if ((this.mUIViewRegistroClienteClient == null))
                {
                    this.mUIViewRegistroClienteClient = new WinClient(this);
                    #region Criterio de búsqueda
                    this.mUIViewRegistroClienteClient.SearchProperties[WinControl.PropertyNames.Name] = "ViewRegistroCliente";
                    this.mUIViewRegistroClienteClient.WindowTitles.Add("ViewRegistroCliente");
                    #endregion
                }
                return this.mUIViewRegistroClienteClient;
            }
        }
        
        public UIEntertextWindow31 UIEntertextWindow3
        {
            get
            {
                if ((this.mUIEntertextWindow3 == null))
                {
                    this.mUIEntertextWindow3 = new UIEntertextWindow31(this);
                }
                return this.mUIEntertextWindow3;
            }
        }
        
        public UITxtGmailWindow UITxtGmailWindow
        {
            get
            {
                if ((this.mUITxtGmailWindow == null))
                {
                    this.mUITxtGmailWindow = new UITxtGmailWindow(this);
                }
                return this.mUITxtGmailWindow;
            }
        }
        
        public UIEntertextWindow4 UIEntertextWindow4
        {
            get
            {
                if ((this.mUIEntertextWindow4 == null))
                {
                    this.mUIEntertextWindow4 = new UIEntertextWindow4(this);
                }
                return this.mUIEntertextWindow4;
            }
        }
        
        public UIEntertextWindow5 UIEntertextWindow5
        {
            get
            {
                if ((this.mUIEntertextWindow5 == null))
                {
                    this.mUIEntertextWindow5 = new UIEntertextWindow5(this);
                }
                return this.mUIEntertextWindow5;
            }
        }
        
        public UIEntertextWindow6 UIEntertextWindow6
        {
            get
            {
                if ((this.mUIEntertextWindow6 == null))
                {
                    this.mUIEntertextWindow6 = new UIEntertextWindow6(this);
                }
                return this.mUIEntertextWindow6;
            }
        }
        
        public UIRegistrarWindow UIRegistrarWindow
        {
            get
            {
                if ((this.mUIRegistrarWindow == null))
                {
                    this.mUIRegistrarWindow = new UIRegistrarWindow(this);
                }
                return this.mUIRegistrarWindow;
            }
        }
        #endregion
        
        #region Fields
        private UIEntertextWindow3 mUIEntertextWindow;
        
        private UIEntertextWindow11 mUIEntertextWindow1;
        
        private UIEntertextWindow21 mUIEntertextWindow2;
        
        private WinClient mUIViewRegistroClienteClient;
        
        private UIEntertextWindow31 mUIEntertextWindow3;
        
        private UITxtGmailWindow mUITxtGmailWindow;
        
        private UIEntertextWindow4 mUIEntertextWindow4;
        
        private UIEntertextWindow5 mUIEntertextWindow5;
        
        private UIEntertextWindow6 mUIEntertextWindow6;
        
        private UIRegistrarWindow mUIRegistrarWindow;
        #endregion
    }
    
    [GeneratedCode("Generador de pruebas de UI codificadas", "16.0.31306.167")]
    public class UIEntertextWindow3 : WinWindow
    {
        
        public UIEntertextWindow3(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Criterio de búsqueda
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "edit";
            this.SearchProperties[WinWindow.PropertyNames.Instance] = "7";
            this.WindowTitles.Add("ViewRegistroCliente");
            #endregion
        }
        
        #region Properties
        public WinEdit UIEditEdit
        {
            get
            {
                if ((this.mUIEditEdit == null))
                {
                    this.mUIEditEdit = new WinEdit(this);
                    #region Criterio de búsqueda
                    this.mUIEditEdit.WindowTitles.Add("ViewRegistroCliente");
                    #endregion
                }
                return this.mUIEditEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUIEditEdit;
        #endregion
    }
    
    [GeneratedCode("Generador de pruebas de UI codificadas", "16.0.31306.167")]
    public class UIEntertextWindow11 : WinWindow
    {
        
        public UIEntertextWindow11(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Criterio de búsqueda
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "edit";
            this.SearchProperties[WinWindow.PropertyNames.Instance] = "6";
            this.WindowTitles.Add("ViewRegistroCliente");
            #endregion
        }
        
        #region Properties
        public WinEdit UIEditEdit
        {
            get
            {
                if ((this.mUIEditEdit == null))
                {
                    this.mUIEditEdit = new WinEdit(this);
                    #region Criterio de búsqueda
                    this.mUIEditEdit.WindowTitles.Add("ViewRegistroCliente");
                    #endregion
                }
                return this.mUIEditEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUIEditEdit;
        #endregion
    }
    
    [GeneratedCode("Generador de pruebas de UI codificadas", "16.0.31306.167")]
    public class UIEntertextWindow21 : WinWindow
    {
        
        public UIEntertextWindow21(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Criterio de búsqueda
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "edit";
            this.SearchProperties[WinWindow.PropertyNames.Instance] = "5";
            this.WindowTitles.Add("ViewRegistroCliente");
            #endregion
        }
        
        #region Properties
        public WinEdit UIEditEdit
        {
            get
            {
                if ((this.mUIEditEdit == null))
                {
                    this.mUIEditEdit = new WinEdit(this);
                    #region Criterio de búsqueda
                    this.mUIEditEdit.WindowTitles.Add("ViewRegistroCliente");
                    #endregion
                }
                return this.mUIEditEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUIEditEdit;
        #endregion
    }
    
    [GeneratedCode("Generador de pruebas de UI codificadas", "16.0.31306.167")]
    public class UIEntertextWindow31 : WinWindow
    {
        
        public UIEntertextWindow31(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Criterio de búsqueda
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "edit";
            this.SearchProperties[WinWindow.PropertyNames.Instance] = "4";
            this.WindowTitles.Add("ViewRegistroCliente");
            #endregion
        }
        
        #region Properties
        public WinEdit UIEditEdit
        {
            get
            {
                if ((this.mUIEditEdit == null))
                {
                    this.mUIEditEdit = new WinEdit(this);
                    #region Criterio de búsqueda
                    this.mUIEditEdit.WindowTitles.Add("ViewRegistroCliente");
                    #endregion
                }
                return this.mUIEditEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUIEditEdit;
        #endregion
    }
    
    [GeneratedCode("Generador de pruebas de UI codificadas", "16.0.31306.167")]
    public class UITxtGmailWindow : WinWindow
    {
        
        public UITxtGmailWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Criterio de búsqueda
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "txtGmail";
            this.WindowTitles.Add("ViewRegistroCliente");
            #endregion
        }
        
        #region Properties
        public WinClient UITxtGmailClient
        {
            get
            {
                if ((this.mUITxtGmailClient == null))
                {
                    this.mUITxtGmailClient = new WinClient(this);
                    #region Criterio de búsqueda
                    this.mUITxtGmailClient.WindowTitles.Add("ViewRegistroCliente");
                    #endregion
                }
                return this.mUITxtGmailClient;
            }
        }
        #endregion
        
        #region Fields
        private WinClient mUITxtGmailClient;
        #endregion
    }
    
    [GeneratedCode("Generador de pruebas de UI codificadas", "16.0.31306.167")]
    public class UIEntertextWindow4 : WinWindow
    {
        
        public UIEntertextWindow4(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Criterio de búsqueda
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "edit";
            this.SearchProperties[WinWindow.PropertyNames.Instance] = "3";
            this.WindowTitles.Add("ViewRegistroCliente");
            #endregion
        }
        
        #region Properties
        public WinEdit UIEditEdit
        {
            get
            {
                if ((this.mUIEditEdit == null))
                {
                    this.mUIEditEdit = new WinEdit(this);
                    #region Criterio de búsqueda
                    this.mUIEditEdit.WindowTitles.Add("ViewRegistroCliente");
                    #endregion
                }
                return this.mUIEditEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUIEditEdit;
        #endregion
    }
    
    [GeneratedCode("Generador de pruebas de UI codificadas", "16.0.31306.167")]
    public class UIEntertextWindow5 : WinWindow
    {
        
        public UIEntertextWindow5(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Criterio de búsqueda
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "edit";
            this.SearchProperties[WinWindow.PropertyNames.Instance] = "2";
            this.WindowTitles.Add("ViewRegistroCliente");
            #endregion
        }
        
        #region Properties
        public WinEdit UIEditEdit
        {
            get
            {
                if ((this.mUIEditEdit == null))
                {
                    this.mUIEditEdit = new WinEdit(this);
                    #region Criterio de búsqueda
                    this.mUIEditEdit.WindowTitles.Add("ViewRegistroCliente");
                    #endregion
                }
                return this.mUIEditEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUIEditEdit;
        #endregion
    }
    
    [GeneratedCode("Generador de pruebas de UI codificadas", "16.0.31306.167")]
    public class UIEntertextWindow6 : WinWindow
    {
        
        public UIEntertextWindow6(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Criterio de búsqueda
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "edit";
            this.WindowTitles.Add("ViewRegistroCliente");
            #endregion
        }
        
        #region Properties
        public WinEdit UIEditEdit
        {
            get
            {
                if ((this.mUIEditEdit == null))
                {
                    this.mUIEditEdit = new WinEdit(this);
                    #region Criterio de búsqueda
                    this.mUIEditEdit.WindowTitles.Add("ViewRegistroCliente");
                    #endregion
                }
                return this.mUIEditEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUIEditEdit;
        #endregion
    }
    
    [GeneratedCode("Generador de pruebas de UI codificadas", "16.0.31306.167")]
    public class UIRegistrarWindow : WinWindow
    {
        
        public UIRegistrarWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Criterio de búsqueda
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "Label";
            this.WindowTitles.Add("ViewRegistroCliente");
            #endregion
        }
        
        #region Properties
        public WinText UIRegistrarText
        {
            get
            {
                if ((this.mUIRegistrarText == null))
                {
                    this.mUIRegistrarText = new WinText(this);
                    #region Criterio de búsqueda
                    this.mUIRegistrarText.SearchProperties[WinText.PropertyNames.Name] = "Registrar";
                    this.mUIRegistrarText.WindowTitles.Add("ViewRegistroCliente");
                    #endregion
                }
                return this.mUIRegistrarText;
            }
        }
        #endregion
        
        #region Fields
        private WinText mUIRegistrarText;
        #endregion
    }
    
    [GeneratedCode("Generador de pruebas de UI codificadas", "16.0.31306.167")]
    public class UIConfirmacionWindow : WinWindow
    {
        
        public UIConfirmacionWindow()
        {
            #region Criterio de búsqueda
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Confirmacion";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "#32770";
            this.WindowTitles.Add("Confirmacion");
            #endregion
        }
        
        #region Properties
        public UIOKWindow1 UIOKWindow
        {
            get
            {
                if ((this.mUIOKWindow == null))
                {
                    this.mUIOKWindow = new UIOKWindow1(this);
                }
                return this.mUIOKWindow;
            }
        }
        #endregion
        
        #region Fields
        private UIOKWindow1 mUIOKWindow;
        #endregion
    }
    
    [GeneratedCode("Generador de pruebas de UI codificadas", "16.0.31306.167")]
    public class UIOKWindow1 : WinWindow
    {
        
        public UIOKWindow1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Criterio de búsqueda
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "2";
            this.WindowTitles.Add("Confirmacion");
            #endregion
        }
        
        #region Properties
        public WinButton UIOKButton
        {
            get
            {
                if ((this.mUIOKButton == null))
                {
                    this.mUIOKButton = new WinButton(this);
                    #region Criterio de búsqueda
                    this.mUIOKButton.SearchProperties[WinButton.PropertyNames.Name] = "OK";
                    this.mUIOKButton.WindowTitles.Add("Confirmacion");
                    #endregion
                }
                return this.mUIOKButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIOKButton;
        #endregion
    }
    
    [GeneratedCode("Generador de pruebas de UI codificadas", "16.0.31306.167")]
    public class UIViewActualizarClientWindow : WinWindow
    {
        
        public UIViewActualizarClientWindow()
        {
            #region Criterio de búsqueda
            this.SearchProperties[WinWindow.PropertyNames.Name] = "ViewActualizarCliente";
            this.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.Window", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("ViewActualizarCliente");
            #endregion
        }
        
        #region Properties
        public UIEntertextWindow7 UIEntertextWindow
        {
            get
            {
                if ((this.mUIEntertextWindow == null))
                {
                    this.mUIEntertextWindow = new UIEntertextWindow7(this);
                }
                return this.mUIEntertextWindow;
            }
        }
        
        public UIEntertextWindow12 UIEntertextWindow1
        {
            get
            {
                if ((this.mUIEntertextWindow1 == null))
                {
                    this.mUIEntertextWindow1 = new UIEntertextWindow12(this);
                }
                return this.mUIEntertextWindow1;
            }
        }
        
        public UIBtnActualizarWindow1 UIBtnActualizarWindow
        {
            get
            {
                if ((this.mUIBtnActualizarWindow == null))
                {
                    this.mUIBtnActualizarWindow = new UIBtnActualizarWindow1(this);
                }
                return this.mUIBtnActualizarWindow;
            }
        }
        #endregion
        
        #region Fields
        private UIEntertextWindow7 mUIEntertextWindow;
        
        private UIEntertextWindow12 mUIEntertextWindow1;
        
        private UIBtnActualizarWindow1 mUIBtnActualizarWindow;
        #endregion
    }
    
    [GeneratedCode("Generador de pruebas de UI codificadas", "16.0.31306.167")]
    public class UIEntertextWindow7 : WinWindow
    {
        
        public UIEntertextWindow7(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Criterio de búsqueda
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "edit";
            this.SearchProperties[WinWindow.PropertyNames.Instance] = "2";
            this.WindowTitles.Add("ViewActualizarCliente");
            #endregion
        }
        
        #region Properties
        public WinEdit UIEditEdit
        {
            get
            {
                if ((this.mUIEditEdit == null))
                {
                    this.mUIEditEdit = new WinEdit(this);
                    #region Criterio de búsqueda
                    this.mUIEditEdit.WindowTitles.Add("ViewActualizarCliente");
                    #endregion
                }
                return this.mUIEditEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUIEditEdit;
        #endregion
    }
    
    [GeneratedCode("Generador de pruebas de UI codificadas", "16.0.31306.167")]
    public class UIEntertextWindow12 : WinWindow
    {
        
        public UIEntertextWindow12(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Criterio de búsqueda
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "edit";
            this.WindowTitles.Add("ViewActualizarCliente");
            #endregion
        }
        
        #region Properties
        public WinEdit UIEditEdit
        {
            get
            {
                if ((this.mUIEditEdit == null))
                {
                    this.mUIEditEdit = new WinEdit(this);
                    #region Criterio de búsqueda
                    this.mUIEditEdit.WindowTitles.Add("ViewActualizarCliente");
                    #endregion
                }
                return this.mUIEditEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUIEditEdit;
        #endregion
    }
    
    [GeneratedCode("Generador de pruebas de UI codificadas", "16.0.31306.167")]
    public class UIBtnActualizarWindow1 : WinWindow
    {
        
        public UIBtnActualizarWindow1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Criterio de búsqueda
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "btnActualizar";
            this.WindowTitles.Add("ViewActualizarCliente");
            #endregion
        }
        
        #region Properties
        public WinClient UIActualizarClient
        {
            get
            {
                if ((this.mUIActualizarClient == null))
                {
                    this.mUIActualizarClient = new WinClient(this);
                    #region Criterio de búsqueda
                    this.mUIActualizarClient.SearchProperties[WinControl.PropertyNames.Name] = "Actualizar";
                    this.mUIActualizarClient.WindowTitles.Add("ViewActualizarCliente");
                    #endregion
                }
                return this.mUIActualizarClient;
            }
        }
        #endregion
        
        #region Fields
        private WinClient mUIActualizarClient;
        #endregion
    }
}
