// ------------------------------------------------------------------------------
//  <auto-generated>
//      Este código lo generó el generador de pruebas automatizadas de IU.
//      Versión: 16.0.0.0
//
//      Los cambios realizados en este archivo pueden provocar un comportamiento incorrecto y se perderán si
//      se vuelve a generar el código.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace CodedUITest_Factura
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.WinControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Generador de pruebas de UI codificadas", "16.0.31306.167")]
    public partial class UIMap
    {
        
        /// <summary>
        /// Buscar Cliente,Agregar Pedido , Buscar Pedidos por Fecha,Generar Factura
        /// </summary>
        public void Recorded_Factura()
        {
            #region Variable Declarations
            WinEdit uIEditEdit = this.UIViewLogWindow.UIEntertextWindow.UIEditEdit;
            WinEdit uIEditEdit1 = this.UIViewLogWindow.UIEntertextWindow1.UIEditEdit;
            WinClient uIIniciarSesionClient = this.UIViewLogWindow.UIBtnIniciarSesionWindow.UIIniciarSesionClient;
            WinButton uIOKButton = this.UIOKWindow.UIOKButton;
            WinText uIFacturaText = this.UIViewPrincipalWindow.UIFacturaWindow.UIFacturaText;
            WinEdit uIEditEdit2 = this.UIViewPrincipalWindow.UIEntertextWindow.UIEditEdit;
            WinClient uIBtnBuscarClient = this.UIViewPrincipalWindow.UIBtnBuscarWindow.UIBtnBuscarClient;
            WinText uIAgregarPedidoText = this.UIViewPrincipalWindow.UIAgregarPedidoWindow.UIAgregarPedidoText;
            WinCell uIItem285Cell = this.UIViewAgregarDetalleFaWindow.UIDgvPedidosWindow.UIDataGridViewTable.UIRow0Row.UIItem285Cell;
            WinText uIAgregarDetallesaFactText = this.UIViewAgregarDetalleFaWindow.UIAgregarDetallesaFactWindow.UIAgregarDetallesaFactText;
            WinText uIGenerarFacturaText = this.UIViewPrincipalWindow.UIGenerarFacturaWindow.UIGenerarFacturaText;
            #endregion

            // Escribir 'Admin' en cuadro de texto 'edit'
            uIEditEdit.Text = this.Recorded_FacturaParams.UIEditEditText;

            // Escribir '123qweu0' en cuadro de texto 'edit'
            uIEditEdit1.Text = this.Recorded_FacturaParams.UIEditEditText1;

            // Clic 'Iniciar Sesion' cliente
            Mouse.Click(uIIniciarSesionClient, new Point(90, 30));

            // Clic 'OK' botón
            Mouse.Click(uIOKButton, new Point(57, 15));

            // Clic 'Factura' etiqueta
            Mouse.Click(uIFacturaText, new Point(27, 9));

            // Escribir '27' en cuadro de texto 'edit'
            uIEditEdit2.Text = this.Recorded_FacturaParams.UIEditEditText2;

            // Clic 'btnBuscar' cliente
            Mouse.Click(uIBtnBuscarClient, new Point(11, 18));

            // Clic 'Agregar Pedido' etiqueta
            Mouse.Click(uIAgregarPedidoText, new Point(14, 12));

            // Clic '28.5' celda
            Mouse.Click(uIItem285Cell, new Point(19, 17));

            // Clic '28.5' celda
            Mouse.Click(uIItem285Cell, new Point(19, 17));

            // Doble clic '28.5' celda
            Mouse.DoubleClick(uIItem285Cell, new Point(19, 17));

            // Clic 'Agregar Detalles a Factura' etiqueta
            Mouse.Click(uIAgregarDetallesaFactText, new Point(116, 8));

            // Clic 'Generar Factura' etiqueta
            Mouse.Click(uIGenerarFacturaText, new Point(61, 1));

            // Clic 'OK' botón
            Mouse.Click(uIOKButton, new Point(28, 13));
        }
        
        #region Properties
        public virtual Recorded_FacturaParams Recorded_FacturaParams
        {
            get
            {
                if ((this.mRecorded_FacturaParams == null))
                {
                    this.mRecorded_FacturaParams = new Recorded_FacturaParams();
                }
                return this.mRecorded_FacturaParams;
            }
        }
        
        public UIViewLogWindow UIViewLogWindow
        {
            get
            {
                if ((this.mUIViewLogWindow == null))
                {
                    this.mUIViewLogWindow = new UIViewLogWindow();
                }
                return this.mUIViewLogWindow;
            }
        }
        
        public UIOKWindow UIOKWindow
        {
            get
            {
                if ((this.mUIOKWindow == null))
                {
                    this.mUIOKWindow = new UIOKWindow();
                }
                return this.mUIOKWindow;
            }
        }
        
        public UIViewPrincipalWindow UIViewPrincipalWindow
        {
            get
            {
                if ((this.mUIViewPrincipalWindow == null))
                {
                    this.mUIViewPrincipalWindow = new UIViewPrincipalWindow();
                }
                return this.mUIViewPrincipalWindow;
            }
        }
        
        public UIViewAgregarDetalleFaWindow UIViewAgregarDetalleFaWindow
        {
            get
            {
                if ((this.mUIViewAgregarDetalleFaWindow == null))
                {
                    this.mUIViewAgregarDetalleFaWindow = new UIViewAgregarDetalleFaWindow();
                }
                return this.mUIViewAgregarDetalleFaWindow;
            }
        }
        #endregion
        
        #region Fields
        private Recorded_FacturaParams mRecorded_FacturaParams;
        
        private UIViewLogWindow mUIViewLogWindow;
        
        private UIOKWindow mUIOKWindow;
        
        private UIViewPrincipalWindow mUIViewPrincipalWindow;
        
        private UIViewAgregarDetalleFaWindow mUIViewAgregarDetalleFaWindow;
        #endregion
    }
    
    /// <summary>
    /// Parámetros que se van a pasar a 'Recorded_Factura'
    /// </summary>
    [GeneratedCode("Generador de pruebas de UI codificadas", "16.0.31306.167")]
    public class Recorded_FacturaParams
    {
        
        #region Fields
        /// <summary>
        /// Escribir 'Admin' en cuadro de texto 'edit'
        /// </summary>
        public string UIEditEditText = "Admin";
        
        /// <summary>
        /// Escribir '123qweu0' en cuadro de texto 'edit'
        /// </summary>
        public string UIEditEditText1 = "123qweu0";
        
        /// <summary>
        /// Escribir '27' en cuadro de texto 'edit'
        /// </summary>
        public string UIEditEditText2 = "27";
        #endregion
    }
    
    [GeneratedCode("Generador de pruebas de UI codificadas", "16.0.31306.167")]
    public class UIViewLogWindow : WinWindow
    {
        
        public UIViewLogWindow()
        {
            #region Criterio de búsqueda
            this.SearchProperties[WinWindow.PropertyNames.Name] = "ViewLog";
            this.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.Window", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("ViewLog");
            #endregion
        }
        
        #region Properties
        public UIEntertextWindow UIEntertextWindow
        {
            get
            {
                if ((this.mUIEntertextWindow == null))
                {
                    this.mUIEntertextWindow = new UIEntertextWindow(this);
                }
                return this.mUIEntertextWindow;
            }
        }
        
        public UIEntertextWindow1 UIEntertextWindow1
        {
            get
            {
                if ((this.mUIEntertextWindow1 == null))
                {
                    this.mUIEntertextWindow1 = new UIEntertextWindow1(this);
                }
                return this.mUIEntertextWindow1;
            }
        }
        
        public UIBtnIniciarSesionWindow UIBtnIniciarSesionWindow
        {
            get
            {
                if ((this.mUIBtnIniciarSesionWindow == null))
                {
                    this.mUIBtnIniciarSesionWindow = new UIBtnIniciarSesionWindow(this);
                }
                return this.mUIBtnIniciarSesionWindow;
            }
        }
        #endregion
        
        #region Fields
        private UIEntertextWindow mUIEntertextWindow;
        
        private UIEntertextWindow1 mUIEntertextWindow1;
        
        private UIBtnIniciarSesionWindow mUIBtnIniciarSesionWindow;
        #endregion
    }
    
    [GeneratedCode("Generador de pruebas de UI codificadas", "16.0.31306.167")]
    public class UIEntertextWindow : WinWindow
    {
        
        public UIEntertextWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Criterio de búsqueda
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "edit";
            this.SearchProperties[WinWindow.PropertyNames.Instance] = "2";
            this.WindowTitles.Add("ViewLog");
            #endregion
        }
        
        #region Properties
        public WinEdit UIEditEdit
        {
            get
            {
                if ((this.mUIEditEdit == null))
                {
                    this.mUIEditEdit = new WinEdit(this);
                    #region Criterio de búsqueda
                    this.mUIEditEdit.WindowTitles.Add("ViewLog");
                    #endregion
                }
                return this.mUIEditEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUIEditEdit;
        #endregion
    }
    
    [GeneratedCode("Generador de pruebas de UI codificadas", "16.0.31306.167")]
    public class UIEntertextWindow1 : WinWindow
    {
        
        public UIEntertextWindow1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Criterio de búsqueda
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "edit";
            this.WindowTitles.Add("ViewLog");
            #endregion
        }
        
        #region Properties
        public WinEdit UIEditEdit
        {
            get
            {
                if ((this.mUIEditEdit == null))
                {
                    this.mUIEditEdit = new WinEdit(this);
                    #region Criterio de búsqueda
                    this.mUIEditEdit.WindowTitles.Add("ViewLog");
                    #endregion
                }
                return this.mUIEditEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUIEditEdit;
        #endregion
    }
    
    [GeneratedCode("Generador de pruebas de UI codificadas", "16.0.31306.167")]
    public class UIBtnIniciarSesionWindow : WinWindow
    {
        
        public UIBtnIniciarSesionWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Criterio de búsqueda
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "btnIniciarSesion";
            this.WindowTitles.Add("ViewLog");
            #endregion
        }
        
        #region Properties
        public WinClient UIIniciarSesionClient
        {
            get
            {
                if ((this.mUIIniciarSesionClient == null))
                {
                    this.mUIIniciarSesionClient = new WinClient(this);
                    #region Criterio de búsqueda
                    this.mUIIniciarSesionClient.SearchProperties[WinControl.PropertyNames.Name] = "Iniciar Sesion";
                    this.mUIIniciarSesionClient.WindowTitles.Add("ViewLog");
                    #endregion
                }
                return this.mUIIniciarSesionClient;
            }
        }
        #endregion
        
        #region Fields
        private WinClient mUIIniciarSesionClient;
        #endregion
    }
    
    [GeneratedCode("Generador de pruebas de UI codificadas", "16.0.31306.167")]
    public class UIOKWindow : WinWindow
    {
        
        public UIOKWindow()
        {
            #region Criterio de búsqueda
            this.SearchProperties[WinWindow.PropertyNames.Name] = "OK";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "Button";
            this.WindowTitles.Add("OK");
            #endregion
        }
        
        #region Properties
        public WinButton UIOKButton
        {
            get
            {
                if ((this.mUIOKButton == null))
                {
                    this.mUIOKButton = new WinButton(this);
                    #region Criterio de búsqueda
                    this.mUIOKButton.SearchProperties[WinButton.PropertyNames.Name] = "OK";
                    this.mUIOKButton.WindowTitles.Add("OK");
                    #endregion
                }
                return this.mUIOKButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIOKButton;
        #endregion
    }
    
    [GeneratedCode("Generador de pruebas de UI codificadas", "16.0.31306.167")]
    public class UIViewPrincipalWindow : WinWindow
    {
        
        public UIViewPrincipalWindow()
        {
            #region Criterio de búsqueda
            this.SearchProperties[WinWindow.PropertyNames.Name] = "ViewPrincipal";
            this.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.Window", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("ViewPrincipal");
            #endregion
        }
        
        #region Properties
        public UIFacturaWindow UIFacturaWindow
        {
            get
            {
                if ((this.mUIFacturaWindow == null))
                {
                    this.mUIFacturaWindow = new UIFacturaWindow(this);
                }
                return this.mUIFacturaWindow;
            }
        }
        
        public UIEntertextWindow2 UIEntertextWindow
        {
            get
            {
                if ((this.mUIEntertextWindow == null))
                {
                    this.mUIEntertextWindow = new UIEntertextWindow2(this);
                }
                return this.mUIEntertextWindow;
            }
        }
        
        public UIBtnBuscarWindow UIBtnBuscarWindow
        {
            get
            {
                if ((this.mUIBtnBuscarWindow == null))
                {
                    this.mUIBtnBuscarWindow = new UIBtnBuscarWindow(this);
                }
                return this.mUIBtnBuscarWindow;
            }
        }
        
        public UIAgregarPedidoWindow UIAgregarPedidoWindow
        {
            get
            {
                if ((this.mUIAgregarPedidoWindow == null))
                {
                    this.mUIAgregarPedidoWindow = new UIAgregarPedidoWindow(this);
                }
                return this.mUIAgregarPedidoWindow;
            }
        }
        
        public UIGenerarFacturaWindow UIGenerarFacturaWindow
        {
            get
            {
                if ((this.mUIGenerarFacturaWindow == null))
                {
                    this.mUIGenerarFacturaWindow = new UIGenerarFacturaWindow(this);
                }
                return this.mUIGenerarFacturaWindow;
            }
        }
        #endregion
        
        #region Fields
        private UIFacturaWindow mUIFacturaWindow;
        
        private UIEntertextWindow2 mUIEntertextWindow;
        
        private UIBtnBuscarWindow mUIBtnBuscarWindow;
        
        private UIAgregarPedidoWindow mUIAgregarPedidoWindow;
        
        private UIGenerarFacturaWindow mUIGenerarFacturaWindow;
        #endregion
    }
    
    [GeneratedCode("Generador de pruebas de UI codificadas", "16.0.31306.167")]
    public class UIFacturaWindow : WinWindow
    {
        
        public UIFacturaWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Criterio de búsqueda
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "Label";
            this.SearchProperties[WinWindow.PropertyNames.Instance] = "5";
            this.WindowTitles.Add("ViewPrincipal");
            #endregion
        }
        
        #region Properties
        public WinText UIFacturaText
        {
            get
            {
                if ((this.mUIFacturaText == null))
                {
                    this.mUIFacturaText = new WinText(this);
                    #region Criterio de búsqueda
                    this.mUIFacturaText.SearchProperties[WinText.PropertyNames.Name] = "Factura";
                    this.mUIFacturaText.WindowTitles.Add("ViewPrincipal");
                    #endregion
                }
                return this.mUIFacturaText;
            }
        }
        #endregion
        
        #region Fields
        private WinText mUIFacturaText;
        #endregion
    }
    
    [GeneratedCode("Generador de pruebas de UI codificadas", "16.0.31306.167")]
    public class UIEntertextWindow2 : WinWindow
    {
        
        public UIEntertextWindow2(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Criterio de búsqueda
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "edit";
            this.SearchProperties[WinWindow.PropertyNames.Instance] = "5";
            this.WindowTitles.Add("ViewPrincipal");
            #endregion
        }
        
        #region Properties
        public WinEdit UIEditEdit
        {
            get
            {
                if ((this.mUIEditEdit == null))
                {
                    this.mUIEditEdit = new WinEdit(this);
                    #region Criterio de búsqueda
                    this.mUIEditEdit.WindowTitles.Add("ViewPrincipal");
                    #endregion
                }
                return this.mUIEditEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUIEditEdit;
        #endregion
    }
    
    [GeneratedCode("Generador de pruebas de UI codificadas", "16.0.31306.167")]
    public class UIBtnBuscarWindow : WinWindow
    {
        
        public UIBtnBuscarWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Criterio de búsqueda
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "btnBuscar";
            this.WindowTitles.Add("ViewPrincipal");
            #endregion
        }
        
        #region Properties
        public WinClient UIBtnBuscarClient
        {
            get
            {
                if ((this.mUIBtnBuscarClient == null))
                {
                    this.mUIBtnBuscarClient = new WinClient(this);
                    #region Criterio de búsqueda
                    this.mUIBtnBuscarClient.WindowTitles.Add("ViewPrincipal");
                    #endregion
                }
                return this.mUIBtnBuscarClient;
            }
        }
        #endregion
        
        #region Fields
        private WinClient mUIBtnBuscarClient;
        #endregion
    }
    
    [GeneratedCode("Generador de pruebas de UI codificadas", "16.0.31306.167")]
    public class UIAgregarPedidoWindow : WinWindow
    {
        
        public UIAgregarPedidoWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Criterio de búsqueda
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "Label";
            this.SearchProperties[WinWindow.PropertyNames.Instance] = "2";
            this.WindowTitles.Add("ViewPrincipal");
            #endregion
        }
        
        #region Properties
        public WinText UIAgregarPedidoText
        {
            get
            {
                if ((this.mUIAgregarPedidoText == null))
                {
                    this.mUIAgregarPedidoText = new WinText(this);
                    #region Criterio de búsqueda
                    this.mUIAgregarPedidoText.SearchProperties[WinText.PropertyNames.Name] = "Agregar Pedido";
                    this.mUIAgregarPedidoText.WindowTitles.Add("ViewPrincipal");
                    #endregion
                }
                return this.mUIAgregarPedidoText;
            }
        }
        #endregion
        
        #region Fields
        private WinText mUIAgregarPedidoText;
        #endregion
    }
    
    [GeneratedCode("Generador de pruebas de UI codificadas", "16.0.31306.167")]
    public class UIGenerarFacturaWindow : WinWindow
    {
        
        public UIGenerarFacturaWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Criterio de búsqueda
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "Label";
            this.WindowTitles.Add("ViewPrincipal");
            #endregion
        }
        
        #region Properties
        public WinText UIGenerarFacturaText
        {
            get
            {
                if ((this.mUIGenerarFacturaText == null))
                {
                    this.mUIGenerarFacturaText = new WinText(this);
                    #region Criterio de búsqueda
                    this.mUIGenerarFacturaText.SearchProperties[WinText.PropertyNames.Name] = "Generar Factura";
                    this.mUIGenerarFacturaText.WindowTitles.Add("ViewPrincipal");
                    #endregion
                }
                return this.mUIGenerarFacturaText;
            }
        }
        #endregion
        
        #region Fields
        private WinText mUIGenerarFacturaText;
        #endregion
    }
    
    [GeneratedCode("Generador de pruebas de UI codificadas", "16.0.31306.167")]
    public class UIViewAgregarDetalleFaWindow : WinWindow
    {
        
        public UIViewAgregarDetalleFaWindow()
        {
            #region Criterio de búsqueda
            this.SearchProperties[WinWindow.PropertyNames.Name] = "ViewAgregarDetalleFactura";
            this.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.Window", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("ViewAgregarDetalleFactura");
            #endregion
        }
        
        #region Properties
        public UIDgvPedidosWindow UIDgvPedidosWindow
        {
            get
            {
                if ((this.mUIDgvPedidosWindow == null))
                {
                    this.mUIDgvPedidosWindow = new UIDgvPedidosWindow(this);
                }
                return this.mUIDgvPedidosWindow;
            }
        }
        
        public UIAgregarDetallesaFactWindow UIAgregarDetallesaFactWindow
        {
            get
            {
                if ((this.mUIAgregarDetallesaFactWindow == null))
                {
                    this.mUIAgregarDetallesaFactWindow = new UIAgregarDetallesaFactWindow(this);
                }
                return this.mUIAgregarDetallesaFactWindow;
            }
        }
        #endregion
        
        #region Fields
        private UIDgvPedidosWindow mUIDgvPedidosWindow;
        
        private UIAgregarDetallesaFactWindow mUIAgregarDetallesaFactWindow;
        #endregion
    }
    
    [GeneratedCode("Generador de pruebas de UI codificadas", "16.0.31306.167")]
    public class UIDgvPedidosWindow : WinWindow
    {
        
        public UIDgvPedidosWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Criterio de búsqueda
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "dgvPedidos";
            this.WindowTitles.Add("ViewAgregarDetalleFactura");
            #endregion
        }
        
        #region Properties
        public UIDataGridViewTable UIDataGridViewTable
        {
            get
            {
                if ((this.mUIDataGridViewTable == null))
                {
                    this.mUIDataGridViewTable = new UIDataGridViewTable(this);
                }
                return this.mUIDataGridViewTable;
            }
        }
        #endregion
        
        #region Fields
        private UIDataGridViewTable mUIDataGridViewTable;
        #endregion
    }
    
    [GeneratedCode("Generador de pruebas de UI codificadas", "16.0.31306.167")]
    public class UIDataGridViewTable : WinTable
    {
        
        public UIDataGridViewTable(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Criterio de búsqueda
            this.SearchProperties[WinTable.PropertyNames.Name] = "DataGridView";
            this.WindowTitles.Add("ViewAgregarDetalleFactura");
            #endregion
        }
        
        #region Properties
        public UIRow0Row UIRow0Row
        {
            get
            {
                if ((this.mUIRow0Row == null))
                {
                    this.mUIRow0Row = new UIRow0Row(this);
                }
                return this.mUIRow0Row;
            }
        }
        #endregion
        
        #region Fields
        private UIRow0Row mUIRow0Row;
        #endregion
    }
    
    [GeneratedCode("Generador de pruebas de UI codificadas", "16.0.31306.167")]
    public class UIRow0Row : WinRow
    {
        
        public UIRow0Row(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Criterio de búsqueda
            this.SearchProperties.Add(new PropertyExpression(WinRow.PropertyNames.Value, ";Koenraad;28.5;11/9/2021 3:19:13 PM", PropertyExpressionOperator.Contains));
            this.SearchConfigurations.Add(SearchConfiguration.AlwaysSearch);
            this.WindowTitles.Add("ViewAgregarDetalleFactura");
            #endregion
        }
        
        #region Properties
        public WinCell UIItem285Cell
        {
            get
            {
                if ((this.mUIItem285Cell == null))
                {
                    this.mUIItem285Cell = new WinCell(this);
                    #region Criterio de búsqueda
                    this.mUIItem285Cell.SearchProperties[WinCell.PropertyNames.Value] = "28.5";
                    this.mUIItem285Cell.WindowTitles.Add("ViewAgregarDetalleFactura");
                    #endregion
                }
                return this.mUIItem285Cell;
            }
        }
        #endregion
        
        #region Fields
        private WinCell mUIItem285Cell;
        #endregion
    }
    
    [GeneratedCode("Generador de pruebas de UI codificadas", "16.0.31306.167")]
    public class UIAgregarDetallesaFactWindow : WinWindow
    {
        
        public UIAgregarDetallesaFactWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Criterio de búsqueda
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "Label";
            this.WindowTitles.Add("ViewAgregarDetalleFactura");
            #endregion
        }
        
        #region Properties
        public WinText UIAgregarDetallesaFactText
        {
            get
            {
                if ((this.mUIAgregarDetallesaFactText == null))
                {
                    this.mUIAgregarDetallesaFactText = new WinText(this);
                    #region Criterio de búsqueda
                    this.mUIAgregarDetallesaFactText.SearchProperties[WinText.PropertyNames.Name] = "Agregar Detalles a Factura";
                    this.mUIAgregarDetallesaFactText.WindowTitles.Add("ViewAgregarDetalleFactura");
                    #endregion
                }
                return this.mUIAgregarDetallesaFactText;
            }
        }
        #endregion
        
        #region Fields
        private WinText mUIAgregarDetallesaFactText;
        #endregion
    }
}
